/**
 * trstctl TypeScript SDK — a thin, dependency-free runtime over the SERVED
 * OpenAPI 3.1 contract. The resource shapes are NOT hand-written: they come from
 * ./types.gen.ts, which is generated by `openapi-typescript` from
 * clients/sdk/openapi.json (pinned byte-for-byte to the live spec by the Go test
 * internal/api.TestSDKSpecPinnedToGolden). So the request/response types here
 * cannot silently drift from the API — regenerate with `npm run gen` (or the
 * repo's `make sdk`) when the contract changes and `tsc` will flag any breakage.
 *
 * What it gives an integrator (mirroring the Go SDK):
 *   - Auth: Authorization: Bearer <token> on every call; optional X-Tenant-ID.
 *   - Idempotency (AN-5): an Idempotency-Key on every mutation, auto-generated
 *     if the caller does not pass one, held stable across automatic retries.
 *   - problem+json (RFC 7807): non-2xx bodies parse into a typed TrstctlProblem
 *     (also an Error) with status/title/detail/type/instance + extensions.
 *   - Retries with backoff: 429/502/503/504 are retried, honoring Retry-After.
 *   - Cursor pagination: list* return { items, next_cursor }; the async
 *     generators paginate* follow next_cursor so callers can `for await` items.
 *
 * Runtime requirement: a global `fetch` (Node 18+, Deno, browsers).
 */

import type { components } from "./types.gen";

type Schemas = components["schemas"];

// Re-export the contract-bound resource types under ergonomic names.
export type Owner = Schemas["Owner"];
export type OwnerRequest = Schemas["OwnerRequest"];
export type OwnerList = Schemas["OwnerList"];
export type Identity = Schemas["Identity"];
export type IdentityRequest = Schemas["IdentityRequest"];
export type IdentityList = Schemas["IdentityList"];
export type TransitionRequest = Schemas["TransitionRequest"];
export type Certificate = Schemas["Certificate"];
export type CertificateHealthDashboard = Schemas["CertificateHealthDashboard"];
export type CertificateList = Schemas["CertificateList"];
export type Problem = Schemas["Problem"];

/** TransitionTo is the set of lifecycle targets the contract accepts. */
export type TransitionTo = TransitionRequest["to"];

/** A single page of a cursor-paginated list. */
export interface Page<T> {
  items: T[];
  next_cursor?: string;
}

/** ListOptions are the common cursor-pagination knobs. */
export interface ListOptions {
  /** items per page (server clamps 1..100, default 20) */
  limit?: number;
  /** opaque cursor from a prior page's next_cursor */
  cursor?: string;
}

/** RetryPolicy configures automatic retries of idempotent failures. */
export interface RetryPolicy {
  /** total attempts (1 = no retry) */
  maxAttempts: number;
  /** first backoff delay in ms; doubles each attempt up to maxDelayMs */
  baseDelayMs: number;
  /** cap on per-attempt backoff in ms */
  maxDelayMs: number;
}

export const DEFAULT_RETRY: RetryPolicy = { maxAttempts: 4, baseDelayMs: 200, maxDelayMs: 5000 };

export interface ClientOptions {
  /** control-plane base URL, e.g. "https://localhost:8443" */
  baseUrl: string;
  /** trstctl API token, sent as Authorization: Bearer <token> */
  token?: string;
  /** optional X-Tenant-ID hint (header/dev auth) */
  tenant?: string;
  /** override the global fetch (e.g. a custom agent / test double) */
  fetch?: typeof fetch;
  /** retry policy; defaults to DEFAULT_RETRY */
  retry?: Partial<RetryPolicy>;
  /** User-Agent override */
  userAgent?: string;
}

/**
 * TrstctlProblem is the typed RFC 7807 error thrown on a non-2xx response. It
 * extends Error so callers can both `instanceof TrstctlProblem` and treat it as
 * a normal error.
 */
export class TrstctlProblem extends Error {
  /** the HTTP status of the response (authoritative) */
  readonly httpStatus: number;
  readonly type?: string;
  readonly title?: string;
  /** the "status" member from the body, if present */
  readonly status?: number;
  readonly detail?: string;
  readonly instance?: string;
  /** any non-standard problem members */
  readonly extensions: Record<string, unknown>;
  /** parsed Retry-After in seconds, if the server sent one (e.g. on 429) */
  readonly retryAfterSeconds?: number;

  constructor(httpStatus: number, body: unknown, retryAfterSeconds?: number) {
    const p = (body && typeof body === "object" ? (body as Record<string, unknown>) : {}) as Record<string, unknown>;
    const title = typeof p.title === "string" ? p.title : undefined;
    const detail = typeof p.detail === "string" ? p.detail : undefined;
    super(`trstctl: ${httpStatus} ${title ?? ""}${detail ? `: ${detail}` : ""}`.trim());
    this.name = "TrstctlProblem";
    this.httpStatus = httpStatus;
    this.type = typeof p.type === "string" ? p.type : undefined;
    this.title = title;
    this.status = typeof p.status === "number" ? p.status : undefined;
    this.detail = detail;
    this.instance = typeof p.instance === "string" ? p.instance : undefined;
    this.retryAfterSeconds = retryAfterSeconds;
    const ext: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(p)) {
      if (!["type", "title", "status", "detail", "instance"].includes(k)) ext[k] = v;
    }
    this.extensions = ext;
  }

  get isRateLimited(): boolean {
    return this.httpStatus === 429;
  }
}

/** newIdempotencyKey returns a fresh key so a retried mutation cannot execute twice (AN-5). */
export function newIdempotencyKey(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c && typeof c.randomUUID === "function") return c.randomUUID();
  return `idem-${Date.now().toString(16)}-${Math.random().toString(16).slice(2)}`;
}

const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"]);

function parseRetryAfter(h: string | null): number | undefined {
  if (!h) return undefined;
  const secs = Number(h);
  if (Number.isFinite(secs)) return Math.max(0, Math.round(secs));
  const when = Date.parse(h);
  if (!Number.isNaN(when)) return Math.max(0, Math.round((when - Date.now()) / 1000));
  return undefined;
}

const RETRYABLE = new Set([429, 502, 503, 504]);

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

interface RequestInitX {
  method?: string;
  query?: Record<string, string | number | undefined>;
  body?: unknown;
  idempotencyKey?: string;
}

/** TrstctlClient is the SDK entry point. */
export class TrstctlClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly tenant?: string;
  private readonly doFetch: typeof fetch;
  private readonly retry: RetryPolicy;
  private readonly userAgent: string;

  constructor(opts: ClientOptions) {
    if (!opts.baseUrl) throw new Error("trstctl: baseUrl is required");
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.token = opts.token;
    this.tenant = opts.tenant;
    const f = opts.fetch ?? (globalThis as { fetch?: typeof fetch }).fetch;
    if (!f) throw new Error("trstctl: no global fetch available; pass opts.fetch");
    this.doFetch = f;
    this.retry = { ...DEFAULT_RETRY, ...(opts.retry ?? {}) };
    this.userAgent = opts.userAgent ?? "trstctl-ts-sdk/1";
  }

  private backoff(attempt: number, retryAfterSeconds?: number): number {
    if (retryAfterSeconds != null) return Math.min(retryAfterSeconds * 1000, this.retry.maxDelayMs);
    let d = this.retry.baseDelayMs;
    for (let i = 1; i < attempt; i++) {
      d *= 2;
      if (d >= this.retry.maxDelayMs) return this.retry.maxDelayMs;
    }
    return d;
  }

  /** request performs an HTTP request with auth, idempotency, retry, and problem+json decoding. */
  async request<T>(path: string, init: RequestInitX = {}): Promise<T> {
    const method = (init.method ?? "GET").toUpperCase();
    let url = this.baseUrl + path;
    if (init.query) {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(init.query)) {
        if (v !== undefined && v !== "") qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += `?${s}`;
    }

    // A mutation gets a stable Idempotency-Key for the whole operation, held
    // constant across retries so a retried POST is exactly-once on the server.
    let idemKey = init.idempotencyKey;
    if (!idemKey && MUTATING.has(method)) idemKey = newIdempotencyKey();

    const headers: Record<string, string> = {
      Accept: "application/json, application/problem+json",
      "User-Agent": this.userAgent,
    };
    if (this.token) headers["Authorization"] = `Bearer ${this.token}`;
    if (this.tenant) headers["X-Tenant-ID"] = this.tenant;
    if (idemKey) headers["Idempotency-Key"] = idemKey;
    let bodyStr: string | undefined;
    if (init.body !== undefined) {
      bodyStr = JSON.stringify(init.body);
      headers["Content-Type"] = "application/json";
    }

    let lastErr: unknown;
    for (let attempt = 1; attempt <= this.retry.maxAttempts; attempt++) {
      let res: Response;
      try {
        res = await this.doFetch(url, { method, headers, body: bodyStr });
      } catch (e) {
        lastErr = e;
        if (attempt < this.retry.maxAttempts) {
          await sleep(this.backoff(attempt));
          continue;
        }
        throw e;
      }

      if (res.ok) {
        if (res.status === 204) return undefined as T;
        const text = await res.text();
        return (text ? JSON.parse(text) : undefined) as T;
      }

      const retryAfter = parseRetryAfter(res.headers.get("Retry-After"));
      let parsed: unknown;
      try {
        parsed = await res.clone().json();
      } catch {
        parsed = { detail: await res.text() };
      }
      const problem = new TrstctlProblem(res.status, parsed, retryAfter);
      lastErr = problem;

      if (RETRYABLE.has(res.status) && attempt < this.retry.maxAttempts) {
        await sleep(this.backoff(attempt, retryAfter));
        continue;
      }
      throw problem;
    }
    throw lastErr;
  }

  // ---- Owners ---------------------------------------------------------------

  createOwner(req: OwnerRequest, idempotencyKey?: string): Promise<Owner> {
    return this.request<Owner>("/api/v1/owners", { method: "POST", body: req, idempotencyKey });
  }
  listOwners(opts: ListOptions = {}): Promise<OwnerList> {
    return this.request<OwnerList>("/api/v1/owners", { query: { limit: opts.limit, cursor: opts.cursor } });
  }
  /** owners is an async generator that pages through every owner via next_cursor. */
  owners(opts: ListOptions = {}): AsyncGenerator<Owner> {
    return this.paginate<Owner>("/api/v1/owners", opts);
  }

  // ---- Identities -----------------------------------------------------------

  createIdentity(req: IdentityRequest, idempotencyKey?: string): Promise<Identity> {
    return this.request<Identity>("/api/v1/identities", { method: "POST", body: req, idempotencyKey });
  }
  getIdentity(id: string): Promise<Identity> {
    return this.request<Identity>(`/api/v1/identities/${encodeURIComponent(id)}`);
  }
  listIdentities(opts: ListOptions = {}): Promise<IdentityList> {
    return this.request<IdentityList>("/api/v1/identities", { query: { limit: opts.limit, cursor: opts.cursor } });
  }
  identities(opts: ListOptions = {}): AsyncGenerator<Identity> {
    return this.paginate<Identity>("/api/v1/identities", opts);
  }
  /** transitionIdentity moves an identity to a new lifecycle state. */
  transitionIdentity(id: string, to: TransitionTo, reason?: string, idempotencyKey?: string): Promise<Identity> {
    const body: TransitionRequest = { to, ...(reason ? { reason } : {}) };
    return this.request<Identity>(`/api/v1/identities/${encodeURIComponent(id)}/transitions`, {
      method: "POST",
      body,
      idempotencyKey,
    });
  }

  // ---- Certificates ---------------------------------------------------------

  listCertificates(opts: ListOptions & { expiringBefore?: string } = {}): Promise<CertificateList> {
    return this.request<CertificateList>("/api/v1/certificates", {
      query: { limit: opts.limit, cursor: opts.cursor, expiring_before: opts.expiringBefore },
    });
  }
  certificates(opts: ListOptions & { expiringBefore?: string } = {}): AsyncGenerator<Certificate> {
    return this.paginate<Certificate>("/api/v1/certificates", opts, {
      expiring_before: opts.expiringBefore,
    });
  }
  certificateHealth(): Promise<CertificateHealthDashboard> {
    return this.request<CertificateHealthDashboard>("/api/v1/certificates/health");
  }

  // ---- Getting-started convenience -----------------------------------------

  /**
   * issueFirstCertificate runs the documented getting-started flow in one call:
   * create a workload owner, create an x509_certificate identity owned by it,
   * and transition that identity to "issued" (which drives the server outbox to
   * mint the certificate). Each step is a mutation with its own Idempotency-Key.
   */
  async issueFirstCertificate(name: string): Promise<Identity> {
    const owner = await this.createOwner({ kind: "workload", name });
    const ident = await this.createIdentity({ kind: "x509_certificate", name, owner_id: owner.id });
    return this.transitionIdentity(ident.id, "issued", "first issuance via TS SDK");
  }

  // ---- Cursor pagination ----------------------------------------------------

  /** paginate yields every item across pages, following next_cursor. */
  private async *paginate<T>(
    path: string,
    opts: ListOptions,
    extraQuery: Record<string, string | number | undefined> = {},
  ): AsyncGenerator<T> {
    let cursor = opts.cursor;
    for (;;) {
      const page = await this.request<Page<T>>(path, {
        query: { limit: opts.limit, cursor, ...extraQuery },
      });
      for (const item of page.items ?? []) yield item;
      if (!page.next_cursor) return;
      cursor = page.next_cursor;
    }
  }
}

/** isProblem narrows an unknown error to a TrstctlProblem. */
export function isProblem(err: unknown): err is TrstctlProblem {
  return err instanceof TrstctlProblem;
}
