package observ_test

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
	"trstctl.com/trstctl/internal/observ"
	"trstctl.com/trstctl/internal/perf"
)

// TestAlertRulesReferenceRealMetrics is the R2.2 "a sample alert fires under an
// induced condition" reality check: every trstctl_ metric the shipped Prometheus
// alert rules reference is actually emitted by the running code, and inducing the
// alert's condition (a 5xx response) moves the metric it watches. A rule that
// referenced a non-existent metric would never fire — this catches that.
func TestAlertRulesReferenceRealMetrics(t *testing.T) {
	data, err := os.ReadFile(filepath.FromSlash("../../deploy/observability/alerts.yml"))
	if err != nil {
		t.Fatalf("read alerts.yml: %v", err)
	}
	refs := uniqueStrings(regexp.MustCompile(`trstctl_[a-z0-9_]+`).FindAllString(string(data), -1))
	if len(refs) == 0 {
		t.Fatal("alerts.yml references no trstctl_ metrics")
	}

	// Induce the alert condition: a request that returns 5xx.
	reg := observ.NewRegistry()
	mw := observ.NewMiddleware(observ.Options{Registry: reg, Tracer: observ.NewTracer(nil)})
	h := mw.Handler(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	h.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/api/v1/owners", nil))

	// Induce the signer alert condition through the shared library (SF.3): a signer
	// that is down after several restarts emits both signer metrics the
	// trstctl-signer rules watch.
	observ.NewSignerMetrics(reg).Observe(false, 4)
	reg.Gauge("trstctl_event_log_replicas_desired", "Configured JetStream replica count required for the source-of-truth event stream.").Set(3)
	reg.Gauge("trstctl_event_log_replicas_actual", "Observed JetStream replica count on the source-of-truth event stream.").Set(1)
	reg.Gauge("trstctl_projection_lag_events", "Number of events the read model is behind the head of the event log.").Set(1001)
	reg.Gauge("trstctl_outbox_reconciliation_lag_events", "Number of events after the last boot reconciliation checkpoint.").Set(1001)
	reg.CounterVec("trstctl_outbox_delivery_timeouts_total", "Outbox deliveries that exceeded their per-message execution timeout.", []string{"tenant_id", "destination"}).WithLabelValues("tenant-a", "webhook").Inc()
	reg.CounterVec("trstctl_read_model_snapshots_written_total", "Read-model snapshots written by the periodic snapshot worker.", nil).WithLabelValues().Inc()
	reg.Gauge("trstctl_read_model_snapshot_last_success_timestamp_seconds", "Unix timestamp of the last successful read-model snapshot.").Set(123)
	reg.CounterVec("trstctl_read_model_snapshot_failures_total", "Read-model snapshot attempts that failed.", nil).WithLabelValues().Inc()
	reg.CounterVec("trstctl_crl_regenerated_total", "CRLs regenerated by the served CRL freshness scheduler.", nil).WithLabelValues().Inc()
	reg.Gauge("trstctl_crl_last_regenerated_timestamp_seconds", "Unix timestamp of the last successful CRL regeneration.").Set(123)
	reg.CounterVec("trstctl_crl_regeneration_failures_total", "CRL freshness scheduler sweeps that failed.", nil).WithLabelValues().Inc()
	reg.CounterVec("trstctl_audit_retention_runs_total", "Audit retention runs that archived at least one segment.", nil).WithLabelValues().Inc()
	reg.CounterVec("trstctl_audit_retention_failures_total", "Audit retention runs that failed.", nil).WithLabelValues().Inc()
	reg.Gauge("trstctl_audit_retention_last_success_timestamp_seconds", "Unix timestamp of the last successful audit retention run.").Set(123)
	reg.CounterVec("trstctl_agent_enrollments_total", "Agent bootstrap enrollment attempts by result.", []string{"result"}).WithLabelValues("failed").Inc()
	reg.CounterVec("trstctl_agent_heartbeats_total", "Agent steady-state heartbeat RPCs by result.", []string{"result"}).WithLabelValues("failed").Inc()
	reg.CounterVec("trstctl_agent_bulkhead_rejections_total", "Agent-channel RPCs rejected by the agent bulkhead.", []string{"method"}).WithLabelValues("heartbeat").Inc()
	reg.Gauge("trstctl_agents_total", "Total agents currently known to the control plane.").Set(10)
	reg.Gauge("trstctl_agents_stale_total", "Agents whose last heartbeat is older than two heartbeat intervals.").Set(1)

	var sb strings.Builder
	if err := reg.WriteProm(&sb); err != nil {
		t.Fatal(err)
	}
	emitted := sb.String()
	for _, m := range refs {
		if !strings.Contains(emitted, m) {
			t.Errorf("alerts.yml references metric %q that the code does not emit", m)
		}
	}
	// The induced 5xx is observable in the metric the error-rate alert watches.
	if !strings.Contains(emitted, `trstctl_http_requests_total{method="GET",route="/api/v1/owners",code="500"} 1`) {
		t.Errorf("the induced 5xx did not increment the error counter:\n%s", emitted)
	}
}

// TestOpsCriticalMetricsHaveAlertCoverage is the OPS-002 reverse coverage guard:
// every metric we rely on for the async spine or fleet-health failure modes must be
// covered by the shipped alert pack. The older one-way test caught broken alert
// expressions, but it could not catch a real metric that operators had no alert for.
func TestOpsCriticalMetricsHaveAlertCoverage(t *testing.T) {
	data, err := os.ReadFile(filepath.FromSlash("../../deploy/observability/alerts.yml"))
	if err != nil {
		t.Fatalf("read alerts.yml: %v", err)
	}
	alerts := string(data)
	for _, metric := range opsCriticalMetrics() {
		if !strings.Contains(alerts, metric) {
			t.Errorf("ops-critical metric %s has no shipped alert coverage", metric)
		}
	}
}

func TestOpsCriticalMetricsListIsStableAndDeduped(t *testing.T) {
	metrics := opsCriticalMetrics()
	if len(metrics) == 0 {
		t.Fatal("ops-critical metric list is empty")
	}
	sorted := slices.Clone(metrics)
	slices.Sort(sorted)
	for i, metric := range sorted {
		if metric == "" {
			t.Fatal("ops-critical metric list contains an empty name")
		}
		if i > 0 && metric == sorted[i-1] {
			t.Fatalf("ops-critical metric list contains duplicate %q", metric)
		}
	}
}

func TestPerfSLOAlertRulesCoverEveryHotPath(t *testing.T) {
	rules := readPrometheusAlertRules(t)
	for _, slo := range perf.HotPaths() {
		p99Seconds := formatPromFloat(float64(slo.P99MS) / 1000)
		errorBudgetRatio := formatPromFloat(slo.ErrorBudgetPercent / 100)

		latencyRecord, ok := findPromRule(rules, func(rule prometheusAlertRule) bool {
			return rule.Record == "trstctl:slo_p99_latency_seconds" &&
				rule.Labels["slo_id"] == slo.ID &&
				rule.Labels["hot_path"] == slo.HotPath
		})
		if !ok {
			t.Errorf("%s (%s) has no p99 latency recording rule", slo.ID, slo.HotPath)
			continue
		}
		if latencyRecord.Labels["slo_p99_seconds"] != p99Seconds {
			t.Errorf("%s p99 latency record labels threshold %q, want %q", slo.ID, latencyRecord.Labels["slo_p99_seconds"], p99Seconds)
		}
		if latencyRecord.Labels["route_match"] == "" {
			t.Errorf("%s p99 latency record is missing the served route denominator", slo.ID)
		}
		if !strings.Contains(latencyRecord.Expr, "trstctl_http_request_duration_seconds_bucket") {
			t.Errorf("%s p99 latency record is not derived from the served HTTP latency histogram", slo.ID)
		}

		latencyAlert, ok := findPromRule(rules, func(rule prometheusAlertRule) bool {
			return rule.Alert == "TrstctlPerfSLOLatency"+compactSLOID(slo.ID) &&
				rule.Labels["slo_id"] == slo.ID &&
				rule.Labels["hot_path"] == slo.HotPath
		})
		if !ok {
			t.Errorf("%s (%s) has no p99 latency threshold alert", slo.ID, slo.HotPath)
		} else {
			if latencyAlert.Labels["slo_p99_seconds"] != p99Seconds {
				t.Errorf("%s latency alert labels threshold %q, want %q", slo.ID, latencyAlert.Labels["slo_p99_seconds"], p99Seconds)
			}
			if !strings.Contains(latencyAlert.Expr, `trstctl:slo_p99_latency_seconds{slo_id="`+slo.ID+`"}`) ||
				!strings.Contains(latencyAlert.Expr, "> "+p99Seconds) {
				t.Errorf("%s latency alert does not enforce the committed p99 threshold %s:\n%s", slo.ID, p99Seconds, latencyAlert.Expr)
			}
		}

		for _, window := range []string{"5m", "1h"} {
			errorRecord, ok := findPromRule(rules, func(rule prometheusAlertRule) bool {
				return rule.Record == "trstctl:slo_error_ratio:"+window &&
					rule.Labels["slo_id"] == slo.ID &&
					rule.Labels["hot_path"] == slo.HotPath
			})
			if !ok {
				t.Errorf("%s (%s) has no %s error-ratio recording rule", slo.ID, slo.HotPath, window)
				continue
			}
			if errorRecord.Labels["error_budget_ratio"] != errorBudgetRatio {
				t.Errorf("%s %s error-ratio record labels budget %q, want %q", slo.ID, window, errorRecord.Labels["error_budget_ratio"], errorBudgetRatio)
			}
			if errorRecord.Labels["route_match"] == "" {
				t.Errorf("%s %s error-ratio record is missing the served route denominator", slo.ID, window)
			}
			if !strings.Contains(errorRecord.Expr, "trstctl_http_requests_total") ||
				!strings.Contains(errorRecord.Expr, "["+window+"]") {
				t.Errorf("%s %s error-ratio record is not derived from served HTTP request counters:\n%s", slo.ID, window, errorRecord.Expr)
			}
		}

		burnAlert, ok := findPromRule(rules, func(rule prometheusAlertRule) bool {
			return rule.Alert == "TrstctlPerfSLOBurnRate"+compactSLOID(slo.ID) &&
				rule.Labels["slo_id"] == slo.ID &&
				rule.Labels["hot_path"] == slo.HotPath
		})
		if !ok {
			t.Errorf("%s (%s) has no multi-window error-budget burn alert", slo.ID, slo.HotPath)
		} else {
			if burnAlert.Labels["error_budget_ratio"] != errorBudgetRatio {
				t.Errorf("%s burn alert labels budget %q, want %q", slo.ID, burnAlert.Labels["error_budget_ratio"], errorBudgetRatio)
			}
			for _, required := range []string{
				`trstctl:slo_error_ratio:5m{slo_id="` + slo.ID + `"}`,
				`trstctl:slo_error_ratio:1h{slo_id="` + slo.ID + `"}`,
				errorBudgetRatio + " * 14.4",
				errorBudgetRatio + " * 6",
			} {
				if !strings.Contains(burnAlert.Expr, required) {
					t.Errorf("%s burn alert does not include %q:\n%s", slo.ID, required, burnAlert.Expr)
				}
			}
		}
	}
}

func opsCriticalMetrics() []string {
	return []string{
		"trstctl_projection_lag_events",
		"trstctl_outbox_reconciliation_lag_events",
		"trstctl_outbox_delivery_timeouts_total",
		"trstctl_read_model_snapshot_last_success_timestamp_seconds",
		"trstctl_read_model_snapshot_failures_total",
		"trstctl_crl_last_regenerated_timestamp_seconds",
		"trstctl_crl_regeneration_failures_total",
		"trstctl_audit_retention_failures_total",
		"trstctl_audit_retention_last_success_timestamp_seconds",
		"trstctl_agent_enrollments_total",
		"trstctl_agent_heartbeats_total",
		"trstctl_agent_bulkhead_rejections_total",
		"trstctl_agents_total",
		"trstctl_agents_stale_total",
	}
}

func uniqueStrings(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

type prometheusAlertFile struct {
	Groups []prometheusAlertGroup `yaml:"groups"`
}

type prometheusAlertGroup struct {
	Name  string                `yaml:"name"`
	Rules []prometheusAlertRule `yaml:"rules"`
}

type prometheusAlertRule struct {
	Alert  string            `yaml:"alert"`
	Record string            `yaml:"record"`
	Expr   string            `yaml:"expr"`
	Labels map[string]string `yaml:"labels"`
}

func readPrometheusAlertRules(t *testing.T) []prometheusAlertRule {
	t.Helper()
	data, err := os.ReadFile(filepath.FromSlash("../../deploy/observability/alerts.yml"))
	if err != nil {
		t.Fatalf("read alerts.yml: %v", err)
	}
	var doc prometheusAlertFile
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse alerts.yml: %v", err)
	}
	var rules []prometheusAlertRule
	for _, group := range doc.Groups {
		rules = append(rules, group.Rules...)
	}
	if len(rules) == 0 {
		t.Fatal("alerts.yml contains no Prometheus rules")
	}
	return rules
}

func findPromRule(rules []prometheusAlertRule, predicate func(prometheusAlertRule) bool) (prometheusAlertRule, bool) {
	for _, rule := range rules {
		if predicate(rule) {
			return rule, true
		}
	}
	return prometheusAlertRule{}, false
}

func compactSLOID(id string) string {
	return strings.ReplaceAll(id, "-", "")
}

func formatPromFloat(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}
