// SPDX-License-Identifier: LicenseRef-trstctl-EE

package agent_test

import (
	"errors"
	"testing"

	"trstctl.com/trstctl/ee/succession"
	"trstctl.com/trstctl/ee/succession/agent"
	"trstctl.com/trstctl/internal/crypto"
)

const (
	deployment = "spiffe://d"
	identity   = "spiffe://d/id"
	tenant     = "t"
)

func ecdsa(t *testing.T) crypto.Signer {
	t.Helper()
	s, err := crypto.NewSoftwareBackend().GenerateKey(crypto.ECDSAP256)
	if err != nil {
		t.Fatal(err)
	}
	return s
}

func newAgent(t *testing.T, pred crypto.Signer) *agent.CoSigner {
	t.Helper()
	a, err := agent.New(agent.Config{DeploymentScope: deployment, IdentityID: identity, TenantID: tenant, Signer: pred})
	if err != nil {
		t.Fatal(err)
	}
	return a
}

// predFields are the signer-supplied predecessor-side commitment fields (the
// successor is filled in by MintWorkloadHeld).
func predFields(predPub []byte) succession.CommitmentFields {
	return succession.CommitmentFields{
		DeploymentScope: deployment, IdentityID: identity, TenantID: tenant,
		PredecessorEpoch: 0, Epoch: 1,
		PredecessorAlg: crypto.ECDSAP256, PredecessorPub: predPub,
		PolicyRef: "p", HashAlg: succession.HashAlgSHA256, NotBefore: 1, NotAfter: 1000,
	}
}

func fullFields(predPub, succPub []byte) succession.CommitmentFields {
	f := predFields(predPub)
	f.SuccessorAlg, f.SuccessorPub = crypto.ECDSAP256, succPub
	return f
}

// TestSuccession_WorkloadHeldPredecessor: the FIG. 5 flow yields a record VerifyRecord
// accepts; the predecessor (first) signature was obtained under signer control by
// verifying it against the commitment the signer supplied (PCAS-claim-19 / INV-1).
func TestSuccession_WorkloadHeldPredecessor(t *testing.T) {
	pred := ecdsa(t)
	succ := ecdsa(t) // successor generated by the signer
	rec, err := agent.MintWorkloadHeld(predFields(pred.Public().DER), newAgent(t, pred), succ)
	if err != nil {
		t.Fatalf("MintWorkloadHeld: %v", err)
	}
	if err := succession.VerifyRecord(rec); err != nil {
		t.Fatalf("VerifyRecord rejected the workload-held record: %v", err)
	}
	// The predecessor limb is the agent's key; the successor limb is the signer's.
	commitment, _ := succession.Commit(rec.Fields)
	if err := crypto.VerifyMessage(pred.Public().DER, commitment, rec.PredecessorAtt); err != nil {
		t.Fatalf("predecessor attestation not from the agent key: %v", err)
	}
	if rec.Fields.SuccessorAlg != succ.Algorithm() || string(rec.Fields.SuccessorPub) != string(succ.Public().DER) {
		t.Fatal("successor not the signer-generated key")
	}
}

// TestAgent_RefusesOpaqueBytes: the agent signs only under its succession co-sign
// Purpose and only a well-formed, domain-separated commitment; a foreign purpose or a
// malformed request is refused (FIG. 5 oracle-prevention).
func TestAgent_RefusesOpaqueBytes(t *testing.T) {
	pred := ecdsa(t)
	a := newAgent(t, pred)
	f := fullFields(pred.Public().DER, ecdsa(t).Public().DER)

	for _, p := range []string{"", "some.other.purpose", "sign-me"} {
		if _, err := a.CoSign(agent.Request{Purpose: p, Fields: f}); !errors.Is(err, agent.ErrForeignPurpose) {
			t.Fatalf("purpose %q: got %v, want ErrForeignPurpose", p, err)
		}
	}
	// Correct purpose + binding but a non-canonical (aliased/malformed) commitment:
	// reconstruction fails, so the agent never signs it.
	bad := f
	bad.HashAlg = "SHA-1"
	if _, err := a.CoSign(agent.Request{Purpose: agent.Purpose, Fields: bad}); !errors.Is(err, agent.ErrMalformed) {
		t.Fatalf("malformed commitment: got %v, want ErrMalformed", err)
	}
}

// TestAgent_RefusesForeignIdentityOrTenant: the agent refuses a commitment naming an
// identity, tenant, deployment, or predecessor key that is not its own (FIG. 5).
func TestAgent_RefusesForeignIdentityOrTenant(t *testing.T) {
	pred := ecdsa(t)
	a := newAgent(t, pred)
	succPub := ecdsa(t).Public().DER

	foreignID := fullFields(pred.Public().DER, succPub)
	foreignID.IdentityID = "spiffe://d/someone-else"
	if _, err := a.CoSign(agent.Request{Purpose: agent.Purpose, Fields: foreignID}); !errors.Is(err, agent.ErrForeignBinding) {
		t.Fatalf("foreign identity: got %v, want ErrForeignBinding", err)
	}
	foreignTenant := fullFields(pred.Public().DER, succPub)
	foreignTenant.TenantID = "other-tenant"
	if _, err := a.CoSign(agent.Request{Purpose: agent.Purpose, Fields: foreignTenant}); !errors.Is(err, agent.ErrForeignBinding) {
		t.Fatalf("foreign tenant: got %v, want ErrForeignBinding", err)
	}
	// A request naming a different predecessor key is refused even for this identity.
	notPred := fullFields(ecdsa(t).Public().DER, succPub)
	if _, err := a.CoSign(agent.Request{Purpose: agent.Purpose, Fields: notPred}); !errors.Is(err, agent.ErrNotPredecessor) {
		t.Fatalf("foreign predecessor key: got %v, want ErrNotPredecessor", err)
	}
}

// TestWorkloadHeld_RequiresInclusionProof: a workload-held-predecessor record is
// rejected by the RP without a valid transparency-log inclusion proof — which is what
// distinguishes the authentic chain from a fork minted with an exfiltrated key.
func TestWorkloadHeld_RequiresInclusionProof(t *testing.T) {
	pred := ecdsa(t)
	rec, err := agent.MintWorkloadHeld(predFields(pred.Public().DER), newAgent(t, pred), ecdsa(t))
	if err != nil {
		t.Fatal(err)
	}
	okVerify := func([]byte) error { return nil }

	// Fork simulation: the record is validly dual-signed (an exfiltrated key could
	// produce this) but is NOT logged — no inclusion proof — so the RP rejects it.
	if err := agent.VerifyWorkloadHeld(rec, okVerify); !errors.Is(err, agent.ErrInclusionRequired) {
		t.Fatalf("unlogged workload-held record: got %v, want ErrInclusionRequired", err)
	}
	// With a present, valid inclusion proof the record is accepted.
	rec.InclusionProof = []byte("inclusion-proof")
	if err := agent.VerifyWorkloadHeld(rec, okVerify); err != nil {
		t.Fatalf("logged workload-held record rejected: %v", err)
	}
	// A present-but-invalid inclusion proof is rejected.
	if err := agent.VerifyWorkloadHeld(rec, func([]byte) error { return errors.New("not included") }); err == nil {
		t.Fatal("a record with an invalid inclusion proof was accepted")
	}
}

// maliciousAgent co-signs a commitment for a DIFFERENT epoch than the signer supplied.
type maliciousAgent struct {
	signer      crypto.Signer
	bumpEpochTo uint64
}

func (m *maliciousAgent) CoSign(req agent.Request) (agent.Response, error) {
	f := req.Fields
	f.Epoch = m.bumpEpochTo // attempt to advance/regress the epoch
	commitment, err := succession.Commit(f)
	if err != nil {
		return agent.Response{}, err
	}
	sig, err := m.signer.Sign(commitment, crypto.SignOptions{Hash: crypto.SHA256})
	if err != nil {
		return agent.Response{}, err
	}
	return agent.Response{Signature: sig}, nil
}

// TestWorkloadHeld_AgentCannotChangeEpoch: the agent cannot advance or regress the
// epoch — a co-signature over any commitment other than the signer's fails the
// signer's verification, so epoch monotonicity stays solely the signer's (AC5).
func TestWorkloadHeld_AgentCannotChangeEpoch(t *testing.T) {
	pred := ecdsa(t)
	mal := &maliciousAgent{signer: pred, bumpEpochTo: 5}
	if _, err := agent.MintWorkloadHeld(predFields(pred.Public().DER), mal, ecdsa(t)); !errors.Is(err, agent.ErrCoSignInvalid) {
		t.Fatalf("agent altered the epoch undetected: got %v, want ErrCoSignInvalid", err)
	}
}
