// Code generated by go run ./scripts/gen-terraform-provider-routes; DO NOT EDIT.
package terraformprovider

const (
	routeCreateProfileMethod     = "POST"
	routeCreateProfilePath       = "/api/v1/profiles"
	routeGetProfileVersionMethod = "GET"
	routeGetProfileVersionPath   = "/api/v1/profiles/{name}/versions/{version}"
	routeIssuePKISecretMethod    = "POST"
	routeIssuePKISecretPath      = "/api/v1/secrets/pki"
	routeCreateSecretMethod      = "POST"
	routeCreateSecretPath        = "/api/v1/secrets/store"
	routeGetSecretMethod         = "GET"
	routeGetSecretPath           = "/api/v1/secrets/store/{name}"
	routeRotateSecretMethod      = "PUT"
	routeRotateSecretPath        = "/api/v1/secrets/store/{name}"
	routeDeleteSecretMethod      = "DELETE"
	routeDeleteSecretPath        = "/api/v1/secrets/store/{name}"
)

var terraformProviderOperationIDs = []string{
	"createProfile",
	"createSecret",
	"deleteSecret",
	"getProfileVersion",
	"getSecret",
	"issuePKISecret",
	"rotateSecret",
}
