// SPDX-License-Identifier: MPL-2.0

// Protocol stub for the isolated signing service (AN-4). This is the wire
// contract the control plane uses to reach trstctl-signer over a Unix domain
// socket (single node) or mTLS (across nodes). It is committed as the reviewed
// protocol design for sprint S1.3; Go code is generated and the service is
// implemented in S1.4.
//
// Design rationale, threat model, and the dependency budget live in
// docs/design/signing-service.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/signing/proto/signer.proto

package signerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Algorithm mirrors internal/crypto.Algorithm. Proprietary algorithms use
// neutral licensed slots; the EE attach seam owns their concrete names.
type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_RSA_2048    Algorithm = 1
	Algorithm_ALGORITHM_RSA_3072    Algorithm = 2
	Algorithm_ALGORITHM_RSA_4096    Algorithm = 3
	Algorithm_ALGORITHM_ECDSA_P256  Algorithm = 4
	Algorithm_ALGORITHM_ECDSA_P384  Algorithm = 5
	Algorithm_ALGORITHM_ECDSA_P521  Algorithm = 6
	Algorithm_ALGORITHM_LICENSED_1  Algorithm = 7
	Algorithm_ALGORITHM_LICENSED_2  Algorithm = 8
	Algorithm_ALGORITHM_LICENSED_3  Algorithm = 9
	Algorithm_ALGORITHM_LICENSED_4  Algorithm = 10
	Algorithm_ALGORITHM_LICENSED_5  Algorithm = 11
	Algorithm_ALGORITHM_LICENSED_6  Algorithm = 12
	Algorithm_ALGORITHM_LICENSED_7  Algorithm = 13
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0:  "ALGORITHM_UNSPECIFIED",
		1:  "ALGORITHM_RSA_2048",
		2:  "ALGORITHM_RSA_3072",
		3:  "ALGORITHM_RSA_4096",
		4:  "ALGORITHM_ECDSA_P256",
		5:  "ALGORITHM_ECDSA_P384",
		6:  "ALGORITHM_ECDSA_P521",
		7:  "ALGORITHM_LICENSED_1",
		8:  "ALGORITHM_LICENSED_2",
		9:  "ALGORITHM_LICENSED_3",
		10: "ALGORITHM_LICENSED_4",
		11: "ALGORITHM_LICENSED_5",
		12: "ALGORITHM_LICENSED_6",
		13: "ALGORITHM_LICENSED_7",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_RSA_2048":    1,
		"ALGORITHM_RSA_3072":    2,
		"ALGORITHM_RSA_4096":    3,
		"ALGORITHM_ECDSA_P256":  4,
		"ALGORITHM_ECDSA_P384":  5,
		"ALGORITHM_ECDSA_P521":  6,
		"ALGORITHM_LICENSED_1":  7,
		"ALGORITHM_LICENSED_2":  8,
		"ALGORITHM_LICENSED_3":  9,
		"ALGORITHM_LICENSED_4":  10,
		"ALGORITHM_LICENSED_5":  11,
		"ALGORITHM_LICENSED_6":  12,
		"ALGORITHM_LICENSED_7":  13,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{0}
}

// Hash mirrors internal/crypto.Hash.
type Hash int32

const (
	Hash_HASH_UNSPECIFIED Hash = 0
	Hash_HASH_SHA256      Hash = 1
	Hash_HASH_SHA384      Hash = 2
	Hash_HASH_SHA512      Hash = 3
)

// Enum value maps for Hash.
var (
	Hash_name = map[int32]string{
		0: "HASH_UNSPECIFIED",
		1: "HASH_SHA256",
		2: "HASH_SHA384",
		3: "HASH_SHA512",
	}
	Hash_value = map[string]int32{
		"HASH_UNSPECIFIED": 0,
		"HASH_SHA256":      1,
		"HASH_SHA384":      2,
		"HASH_SHA512":      3,
	}
)

func (x Hash) Enum() *Hash {
	p := new(Hash)
	*p = x
	return p
}

func (x Hash) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hash) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[1].Descriptor()
}

func (Hash) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[1]
}

func (x Hash) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hash.Descriptor instead.
func (Hash) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{1}
}

// RSAPadding mirrors internal/crypto.RSAPadding; ignored for non-RSA keys.
type RSAPadding int32

const (
	RSAPadding_RSA_PADDING_UNSPECIFIED RSAPadding = 0 // treated as PKCS#1 v1.5
	RSAPadding_RSA_PADDING_PKCS1V15    RSAPadding = 1
	RSAPadding_RSA_PADDING_PSS         RSAPadding = 2
)

// Enum value maps for RSAPadding.
var (
	RSAPadding_name = map[int32]string{
		0: "RSA_PADDING_UNSPECIFIED",
		1: "RSA_PADDING_PKCS1V15",
		2: "RSA_PADDING_PSS",
	}
	RSAPadding_value = map[string]int32{
		"RSA_PADDING_UNSPECIFIED": 0,
		"RSA_PADDING_PKCS1V15":    1,
		"RSA_PADDING_PSS":         2,
	}
)

func (x RSAPadding) Enum() *RSAPadding {
	p := new(RSAPadding)
	*p = x
	return p
}

func (x RSAPadding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSAPadding) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[2].Descriptor()
}

func (RSAPadding) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[2]
}

func (x RSAPadding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RSAPadding.Descriptor instead.
func (RSAPadding) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{2}
}

// KeyPurpose is a coarse, signer-enforceable usage class for a key (design
// §4.5). A key may be created with an allowed-purpose set; Sign then carries the
// purpose the caller asserts the signature is for, and the signer refuses any
// Sign whose purpose is outside the key's set (FAILED_PRECONDITION). This is the
// one cheap defense-in-depth the signer can enforce against an abused control
// plane: a key minted for, say, leaf TLS cannot be coerced into signing a CA
// cross-sign or an SSH/code-signing certificate. It bounds, but does not
// eliminate, key abuse (which is fully addressed only by HSMs/dual control).
type KeyPurpose int32

const (
	KeyPurpose_KEY_PURPOSE_UNSPECIFIED KeyPurpose = 0 // no purpose asserted; rejected by a constrained key
	KeyPurpose_KEY_PURPOSE_CA_SIGN     KeyPurpose = 1 // sign CA/intermediate/leaf X.509 certificates
	KeyPurpose_KEY_PURPOSE_LEAF_TLS    KeyPurpose = 2 // sign leaf TLS certificates only
	KeyPurpose_KEY_PURPOSE_SSH_CERT    KeyPurpose = 3 // sign SSH certificates
	KeyPurpose_KEY_PURPOSE_CODE_SIGN   KeyPurpose = 4 // produce code-signing signatures
	KeyPurpose_KEY_PURPOSE_GENERIC     KeyPurpose = 5 // unclassified signing (e.g. test/CSR self-sign)
)

// Enum value maps for KeyPurpose.
var (
	KeyPurpose_name = map[int32]string{
		0: "KEY_PURPOSE_UNSPECIFIED",
		1: "KEY_PURPOSE_CA_SIGN",
		2: "KEY_PURPOSE_LEAF_TLS",
		3: "KEY_PURPOSE_SSH_CERT",
		4: "KEY_PURPOSE_CODE_SIGN",
		5: "KEY_PURPOSE_GENERIC",
	}
	KeyPurpose_value = map[string]int32{
		"KEY_PURPOSE_UNSPECIFIED": 0,
		"KEY_PURPOSE_CA_SIGN":     1,
		"KEY_PURPOSE_LEAF_TLS":    2,
		"KEY_PURPOSE_SSH_CERT":    3,
		"KEY_PURPOSE_CODE_SIGN":   4,
		"KEY_PURPOSE_GENERIC":     5,
	}
)

func (x KeyPurpose) Enum() *KeyPurpose {
	p := new(KeyPurpose)
	*p = x
	return p
}

func (x KeyPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[3].Descriptor()
}

func (KeyPurpose) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[3]
}

func (x KeyPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyPurpose.Descriptor instead.
func (KeyPurpose) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{3}
}

type HealthResponse_Status int32

const (
	HealthResponse_STATUS_UNSPECIFIED HealthResponse_Status = 0
	HealthResponse_STATUS_SERVING     HealthResponse_Status = 1
	HealthResponse_STATUS_NOT_SERVING HealthResponse_Status = 2
	HealthResponse_STATUS_DRAINING    HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SERVING",
		2: "STATUS_NOT_SERVING",
		3: "STATUS_DRAINING",
	}
	HealthResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SERVING":     1,
		"STATUS_NOT_SERVING": 2,
		"STATUS_DRAINING":    3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[4].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[4]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{10, 0}
}

// KeyHandle is an opaque, unguessable reference to a private key held by the
// signer. The control plane stores the handle and the public key; it never sees
// the private key bytes.
type KeyHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHandle) Reset() {
	*x = KeyHandle{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHandle) ProtoMessage() {}

func (x *KeyHandle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHandle.ProtoReflect.Descriptor instead.
func (*KeyHandle) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{0}
}

func (x *KeyHandle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateKeyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Algorithm Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	// Optional caller-chosen handle id for idempotent creation; empty means the
	// signer assigns one.
	RequestedId string `protobuf:"bytes,2,opt,name=requested_id,json=requestedId,proto3" json:"requested_id,omitempty"`
	// allowed_purposes constrains what the key may sign (design §4.5). When
	// non-empty, the signer refuses any Sign whose asserted purpose is not in this
	// set. An empty set means unconstrained (back-compat with pre-constraint
	// callers); the control plane sets a tight set for CA-class keys.
	AllowedPurposes []KeyPurpose `protobuf:"varint,3,rep,packed,name=allowed_purposes,json=allowedPurposes,proto3,enum=trstctl.signing.v1.KeyPurpose" json:"allowed_purposes,omitempty"`
	// allowed_hashes optionally constrains which digest algorithms the key may
	// sign. When non-empty, a Sign with a hash outside the set is refused. Empty
	// means any supported hash is allowed.
	AllowedHashes []Hash `protobuf:"varint,4,rep,packed,name=allowed_hashes,json=allowedHashes,proto3,enum=trstctl.signing.v1.Hash" json:"allowed_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GenerateKeyRequest) GetRequestedId() string {
	if x != nil {
		return x.RequestedId
	}
	return ""
}

func (x *GenerateKeyRequest) GetAllowedPurposes() []KeyPurpose {
	if x != nil {
		return x.AllowedPurposes
	}
	return nil
}

func (x *GenerateKeyRequest) GetAllowedHashes() []Hash {
	if x != nil {
		return x.AllowedHashes
	}
	return nil
}

type GenerateKeyResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Handle    *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Algorithm Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	// public_key is the PKIX/DER (SubjectPublicKeyInfo) encoding.
	PublicKey     []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyResponse) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *GenerateKeyResponse) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GenerateKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublicKeyResponse) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// digest is the pre-computed message digest to sign. Signing a digest (rather
	// than a raw message) is the canonical signer operation: it matches
	// crypto.Signer/HSM semantics and is what X.509 CSR and certificate signing
	// require.
	Digest []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// hash identifies the algorithm that produced digest (needed for RSA).
	Hash       Hash       `protobuf:"varint,3,opt,name=hash,proto3,enum=trstctl.signing.v1.Hash" json:"hash,omitempty"`
	RsaPadding RSAPadding `protobuf:"varint,4,opt,name=rsa_padding,json=rsaPadding,proto3,enum=trstctl.signing.v1.RSAPadding" json:"rsa_padding,omitempty"`
	// purpose is the usage class the caller asserts this signature is for. If the
	// key was created with a non-empty allowed_purposes set, the signer enforces
	// purpose membership and refuses a mismatch with FAILED_PRECONDITION (design
	// §4.5/§5.5). For an unconstrained key it is advisory and may be left
	// UNSPECIFIED.
	Purpose KeyPurpose `protobuf:"varint,5,opt,name=purpose,proto3,enum=trstctl.signing.v1.KeyPurpose" json:"purpose,omitempty"`
	// authorization_token is the raw dual-control authorization token for this exact
	// signing tuple. It stays byte-native across the gRPC boundary so callers and the
	// signer can wipe their owned buffers after use.
	AuthorizationToken []byte `protobuf:"bytes,6,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{5}
}

func (x *SignRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *SignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *SignRequest) GetHash() Hash {
	if x != nil {
		return x.Hash
	}
	return Hash_HASH_UNSPECIFIED
}

func (x *SignRequest) GetRsaPadding() RSAPadding {
	if x != nil {
		return x.RsaPadding
	}
	return RSAPadding_RSA_PADDING_UNSPECIFIED
}

func (x *SignRequest) GetPurpose() KeyPurpose {
	if x != nil {
		return x.Purpose
	}
	return KeyPurpose_KEY_PURPOSE_UNSPECIFIED
}

func (x *SignRequest) GetAuthorizationToken() []byte {
	if x != nil {
		return x.AuthorizationToken
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{6}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DestroyKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKeyRequest) Reset() {
	*x = DestroyKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKeyRequest) ProtoMessage() {}

func (x *DestroyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKeyRequest.ProtoReflect.Descriptor instead.
func (*DestroyKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyKeyRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DestroyKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKeyResponse) Reset() {
	*x = DestroyKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKeyResponse) ProtoMessage() {}

func (x *DestroyKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKeyResponse.ProtoReflect.Descriptor instead.
func (*DestroyKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{8}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=trstctl.signing.v1.HealthResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_STATUS_UNSPECIFIED
}

// MintSuccessorRequest mirrors internal/signing.MintRequest (INT-01). It carries
// NO private key material: the predecessor is a handle held inside the signer, and
// every authorization/policy/attestation input is opaque bytes verified in-signer
// before any successor key is generated.
type MintSuccessorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdentityId      string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeploymentScope string                 `protobuf:"bytes,3,opt,name=deployment_scope,json=deploymentScope,proto3" json:"deployment_scope,omitempty"`
	// predecessor_handle is the opaque in-signer handle of the predecessor key. The
	// control plane never sees the predecessor private key bytes.
	PredecessorHandle        string    `protobuf:"bytes,4,opt,name=predecessor_handle,json=predecessorHandle,proto3" json:"predecessor_handle,omitempty"`
	AssertedPredecessorEpoch uint64    `protobuf:"varint,5,opt,name=asserted_predecessor_epoch,json=assertedPredecessorEpoch,proto3" json:"asserted_predecessor_epoch,omitempty"`
	TargetAlgorithm          Algorithm `protobuf:"varint,6,opt,name=target_algorithm,json=targetAlgorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"target_algorithm,omitempty"`
	PolicyRef                string    `protobuf:"bytes,7,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	PolicyDecision           []byte    `protobuf:"bytes,8,opt,name=policy_decision,json=policyDecision,proto3" json:"policy_decision,omitempty"` // signed policy artifact (optional)
	Authorization            []byte    `protobuf:"bytes,9,opt,name=authorization,proto3" json:"authorization,omitempty"`                         // dual-control authorization token (optional)
	BreakGlass               []byte    `protobuf:"bytes,10,opt,name=break_glass,json=breakGlass,proto3" json:"break_glass,omitempty"`            // strength-downgrade break-glass token (optional)
	Attestation              []byte    `protobuf:"bytes,11,opt,name=attestation,proto3" json:"attestation,omitempty"`                            // successor-custodian attestation evidence (optional)
	NotBefore                int64     `protobuf:"varint,12,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter                 int64     `protobuf:"varint,13,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MintSuccessorRequest) Reset() {
	*x = MintSuccessorRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSuccessorRequest) ProtoMessage() {}

func (x *MintSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSuccessorRequest.ProtoReflect.Descriptor instead.
func (*MintSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{11}
}

func (x *MintSuccessorRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *MintSuccessorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MintSuccessorRequest) GetDeploymentScope() string {
	if x != nil {
		return x.DeploymentScope
	}
	return ""
}

func (x *MintSuccessorRequest) GetPredecessorHandle() string {
	if x != nil {
		return x.PredecessorHandle
	}
	return ""
}

func (x *MintSuccessorRequest) GetAssertedPredecessorEpoch() uint64 {
	if x != nil {
		return x.AssertedPredecessorEpoch
	}
	return 0
}

func (x *MintSuccessorRequest) GetTargetAlgorithm() Algorithm {
	if x != nil {
		return x.TargetAlgorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *MintSuccessorRequest) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *MintSuccessorRequest) GetPolicyDecision() []byte {
	if x != nil {
		return x.PolicyDecision
	}
	return nil
}

func (x *MintSuccessorRequest) GetAuthorization() []byte {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *MintSuccessorRequest) GetBreakGlass() []byte {
	if x != nil {
		return x.BreakGlass
	}
	return nil
}

func (x *MintSuccessorRequest) GetAttestation() []byte {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *MintSuccessorRequest) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *MintSuccessorRequest) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

// MintSuccessorResponse mirrors internal/signing.MintResult (INT-01). It carries
// only public material: the successor public key and the opaque encoded dual-signed
// succession record. No private key crosses the boundary.
type MintSuccessorResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Epoch              uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SuccessorAlgorithm Algorithm              `protobuf:"varint,2,opt,name=successor_algorithm,json=successorAlgorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"successor_algorithm,omitempty"`
	SuccessorPublicKey []byte                 `protobuf:"bytes,3,opt,name=successor_public_key,json=successorPublicKey,proto3" json:"successor_public_key,omitempty"` // PKIX/DER (SubjectPublicKeyInfo)
	EncodedRecord      []byte                 `protobuf:"bytes,4,opt,name=encoded_record,json=encodedRecord,proto3" json:"encoded_record,omitempty"`                  // opaque dual-signed succession record
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MintSuccessorResponse) Reset() {
	*x = MintSuccessorResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSuccessorResponse) ProtoMessage() {}

func (x *MintSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSuccessorResponse.ProtoReflect.Descriptor instead.
func (*MintSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{12}
}

func (x *MintSuccessorResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MintSuccessorResponse) GetSuccessorAlgorithm() Algorithm {
	if x != nil {
		return x.SuccessorAlgorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *MintSuccessorResponse) GetSuccessorPublicKey() []byte {
	if x != nil {
		return x.SuccessorPublicKey
	}
	return nil
}

func (x *MintSuccessorResponse) GetEncodedRecord() []byte {
	if x != nil {
		return x.EncodedRecord
	}
	return nil
}

// GatedIssueRequest mirrors internal/signing.IssuancePreconditions (AGID-04a seam). It
// carries NO private key material: the delegation chain, attestation evidence, and
// agent-stack representation are opaque bytes the isolated signer's attached issuance gate
// re-verifies cryptographically before any key op, and the scalars are non-secret asserted
// context. The signer never parses the opaque bodies; it forwards them to the gate, whose
// meaning the attached edition defines.
type GatedIssueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id scopes the request to a tenant (AN-1).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// trust_anchor_ref is the asserted trust-anchor reference the caller claims this
	// issuance derives from (an opaque subject handle). The gate resolves and checks it.
	TrustAnchorRef string `protobuf:"bytes,2,opt,name=trust_anchor_ref,json=trustAnchorRef,proto3" json:"trust_anchor_ref,omitempty"`
	// not_before / not_after are the asserted validity bounds (Unix seconds) for the
	// credential to be issued. The gate decides whether they are acceptable.
	NotBefore int64 `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  int64 `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// preconditions is the opaque precondition body (the serialized delegation chain +
	// designated class + task envelope + reachability verdict). Opaque to the signer core.
	Preconditions []byte `protobuf:"bytes,5,opt,name=preconditions,proto3" json:"preconditions,omitempty"`
	// subject_repr is the opaque agent-stack representation to bind into the issued
	// credential. Opaque to the signer core.
	SubjectRepr []byte `protobuf:"bytes,6,opt,name=subject_repr,json=subjectRepr,proto3" json:"subject_repr,omitempty"`
	// attestation is the opaque attestation evidence accompanying the request;
	// attestation_method names the method that produced it. Both opaque to the signer core.
	Attestation       []byte `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	AttestationMethod string `protobuf:"bytes,8,opt,name=attestation_method,json=attestationMethod,proto3" json:"attestation_method,omitempty"`
	// algorithm is the agent-credential key algorithm to generate INSIDE the signer on an
	// approved issuance (the key never leaves the boundary; only its certified public form
	// returns). Unspecified means the issuance key-op picks its default.
	Algorithm     Algorithm `protobuf:"varint,9,opt,name=algorithm,proto3,enum=trstctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatedIssueRequest) Reset() {
	*x = GatedIssueRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatedIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatedIssueRequest) ProtoMessage() {}

func (x *GatedIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatedIssueRequest.ProtoReflect.Descriptor instead.
func (*GatedIssueRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{13}
}

func (x *GatedIssueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GatedIssueRequest) GetTrustAnchorRef() string {
	if x != nil {
		return x.TrustAnchorRef
	}
	return ""
}

func (x *GatedIssueRequest) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *GatedIssueRequest) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *GatedIssueRequest) GetPreconditions() []byte {
	if x != nil {
		return x.Preconditions
	}
	return nil
}

func (x *GatedIssueRequest) GetSubjectRepr() []byte {
	if x != nil {
		return x.SubjectRepr
	}
	return nil
}

func (x *GatedIssueRequest) GetAttestation() []byte {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *GatedIssueRequest) GetAttestationMethod() string {
	if x != nil {
		return x.AttestationMethod
	}
	return ""
}

func (x *GatedIssueRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

// GatedIssueResponse mirrors internal/signing.IssuanceDecision. It carries ONLY non-secret
// material: whether the issuance was approved, the opaque signed refusal record on a
// refusal, and — on approval — the opaque binding material, the issued credential's public
// DER, and the opaque encoded issuance record. No private key crosses the boundary.
type GatedIssueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// approved is true only when the gate approved and the key op minted a credential. When
	// false, refusal_record carries the signer's signed refusal and no key op was performed.
	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	// refusal_record is the opaque signed refusal artifact the gate produced on a refusal
	// (Approved=false). Empty on an approval.
	RefusalRecord []byte `protobuf:"bytes,2,opt,name=refusal_record,json=refusalRecord,proto3" json:"refusal_record,omitempty"`
	// binding_material is the opaque binding the gate bound into the credential (for example
	// the chain-digest + agent-stack commitment). Empty on a refusal.
	BindingMaterial []byte `protobuf:"bytes,3,opt,name=binding_material,json=bindingMaterial,proto3" json:"binding_material,omitempty"`
	// credential_public_der is the DER (PKIX SubjectPublicKeyInfo) of the issued credential
	// — the certified agent credential's public form. Public material only; empty on refusal.
	CredentialPublicDer []byte `protobuf:"bytes,4,opt,name=credential_public_der,json=credentialPublicDer,proto3" json:"credential_public_der,omitempty"`
	// encoded_record is the opaque encoded issuance record the key op produced (for example
	// the issued certificate DER carrying the binding extension). Empty on a refusal.
	EncodedRecord []byte `protobuf:"bytes,5,opt,name=encoded_record,json=encodedRecord,proto3" json:"encoded_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatedIssueResponse) Reset() {
	*x = GatedIssueResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatedIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatedIssueResponse) ProtoMessage() {}

func (x *GatedIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatedIssueResponse.ProtoReflect.Descriptor instead.
func (*GatedIssueResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{14}
}

func (x *GatedIssueResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *GatedIssueResponse) GetRefusalRecord() []byte {
	if x != nil {
		return x.RefusalRecord
	}
	return nil
}

func (x *GatedIssueResponse) GetBindingMaterial() []byte {
	if x != nil {
		return x.BindingMaterial
	}
	return nil
}

func (x *GatedIssueResponse) GetCredentialPublicDer() []byte {
	if x != nil {
		return x.CredentialPublicDer
	}
	return nil
}

func (x *GatedIssueResponse) GetEncodedRecord() []byte {
	if x != nil {
		return x.EncodedRecord
	}
	return nil
}

var File_internal_signing_proto_signer_proto protoreflect.FileDescriptor

const file_internal_signing_proto_signer_proto_rawDesc = "" +
	"\n" +
	"#internal/signing/proto/signer.proto\x12\x12trstctl.signing.v1\"\x1b\n" +
	"\tKeyHandle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x02\n" +
	"\x12GenerateKeyRequest\x12;\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\talgorithm\x12!\n" +
	"\frequested_id\x18\x02 \x01(\tR\vrequestedId\x12I\n" +
	"\x10allowed_purposes\x18\x03 \x03(\x0e2\x1e.trstctl.signing.v1.KeyPurposeR\x0fallowedPurposes\x12?\n" +
	"\x0eallowed_hashes\x18\x04 \x03(\x0e2\x18.trstctl.signing.v1.HashR\rallowedHashes\"\xa8\x01\n" +
	"\x13GenerateKeyResponse\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.trstctl.signing.v1.KeyHandleR\x06handle\x12;\n" +
	"\talgorithm\x18\x02 \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"L\n" +
	"\x13GetPublicKeyRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.trstctl.signing.v1.KeyHandleR\x06handle\"r\n" +
	"\x14GetPublicKeyResponse\x12;\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xb6\x02\n" +
	"\vSignRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.trstctl.signing.v1.KeyHandleR\x06handle\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12,\n" +
	"\x04hash\x18\x03 \x01(\x0e2\x18.trstctl.signing.v1.HashR\x04hash\x12?\n" +
	"\vrsa_padding\x18\x04 \x01(\x0e2\x1e.trstctl.signing.v1.RSAPaddingR\n" +
	"rsaPadding\x128\n" +
	"\apurpose\x18\x05 \x01(\x0e2\x1e.trstctl.signing.v1.KeyPurposeR\apurpose\x12/\n" +
	"\x13authorization_token\x18\x06 \x01(\fR\x12authorizationToken\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"J\n" +
	"\x11DestroyKeyRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.trstctl.signing.v1.KeyHandleR\x06handle\"\x14\n" +
	"\x12DestroyKeyResponse\"\x0f\n" +
	"\rHealthRequest\"\xb6\x01\n" +
	"\x0eHealthResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).trstctl.signing.v1.HealthResponse.StatusR\x06status\"a\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DRAINING\x10\x03\"\xa3\x04\n" +
	"\x14MintSuccessorRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12)\n" +
	"\x10deployment_scope\x18\x03 \x01(\tR\x0fdeploymentScope\x12-\n" +
	"\x12predecessor_handle\x18\x04 \x01(\tR\x11predecessorHandle\x12<\n" +
	"\x1aasserted_predecessor_epoch\x18\x05 \x01(\x04R\x18assertedPredecessorEpoch\x12H\n" +
	"\x10target_algorithm\x18\x06 \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\x0ftargetAlgorithm\x12\x1d\n" +
	"\n" +
	"policy_ref\x18\a \x01(\tR\tpolicyRef\x12'\n" +
	"\x0fpolicy_decision\x18\b \x01(\fR\x0epolicyDecision\x12$\n" +
	"\rauthorization\x18\t \x01(\fR\rauthorization\x12\x1f\n" +
	"\vbreak_glass\x18\n" +
	" \x01(\fR\n" +
	"breakGlass\x12 \n" +
	"\vattestation\x18\v \x01(\fR\vattestation\x12\x1d\n" +
	"\n" +
	"not_before\x18\f \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\r \x01(\x03R\bnotAfter\"\xd6\x01\n" +
	"\x15MintSuccessorResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12N\n" +
	"\x13successor_algorithm\x18\x02 \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\x12successorAlgorithm\x120\n" +
	"\x14successor_public_key\x18\x03 \x01(\fR\x12successorPublicKey\x12%\n" +
	"\x0eencoded_record\x18\x04 \x01(\fR\rencodedRecord\"\xed\x02\n" +
	"\x11GatedIssueRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12(\n" +
	"\x10trust_anchor_ref\x18\x02 \x01(\tR\x0etrustAnchorRef\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\x03R\bnotAfter\x12$\n" +
	"\rpreconditions\x18\x05 \x01(\fR\rpreconditions\x12!\n" +
	"\fsubject_repr\x18\x06 \x01(\fR\vsubjectRepr\x12 \n" +
	"\vattestation\x18\a \x01(\fR\vattestation\x12-\n" +
	"\x12attestation_method\x18\b \x01(\tR\x11attestationMethod\x12;\n" +
	"\talgorithm\x18\t \x01(\x0e2\x1d.trstctl.signing.v1.AlgorithmR\talgorithm\"\xdd\x01\n" +
	"\x12GatedIssueResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12%\n" +
	"\x0erefusal_record\x18\x02 \x01(\fR\rrefusalRecord\x12)\n" +
	"\x10binding_material\x18\x03 \x01(\fR\x0fbindingMaterial\x122\n" +
	"\x15credential_public_der\x18\x04 \x01(\fR\x13credentialPublicDer\x12%\n" +
	"\x0eencoded_record\x18\x05 \x01(\fR\rencodedRecord*\xf2\x02\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ALGORITHM_RSA_2048\x10\x01\x12\x16\n" +
	"\x12ALGORITHM_RSA_3072\x10\x02\x12\x16\n" +
	"\x12ALGORITHM_RSA_4096\x10\x03\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P256\x10\x04\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P384\x10\x05\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P521\x10\x06\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_1\x10\a\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_2\x10\b\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_3\x10\t\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_4\x10\n" +
	"\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_5\x10\v\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_6\x10\f\x12\x18\n" +
	"\x14ALGORITHM_LICENSED_7\x10\r*O\n" +
	"\x04Hash\x12\x14\n" +
	"\x10HASH_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vHASH_SHA256\x10\x01\x12\x0f\n" +
	"\vHASH_SHA384\x10\x02\x12\x0f\n" +
	"\vHASH_SHA512\x10\x03*X\n" +
	"\n" +
	"RSAPadding\x12\x1b\n" +
	"\x17RSA_PADDING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RSA_PADDING_PKCS1V15\x10\x01\x12\x13\n" +
	"\x0fRSA_PADDING_PSS\x10\x02*\xaa\x01\n" +
	"\n" +
	"KeyPurpose\x12\x1b\n" +
	"\x17KEY_PURPOSE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KEY_PURPOSE_CA_SIGN\x10\x01\x12\x18\n" +
	"\x14KEY_PURPOSE_LEAF_TLS\x10\x02\x12\x18\n" +
	"\x14KEY_PURPOSE_SSH_CERT\x10\x03\x12\x19\n" +
	"\x15KEY_PURPOSE_CODE_SIGN\x10\x04\x12\x17\n" +
	"\x13KEY_PURPOSE_GENERIC\x10\x052\x8e\x05\n" +
	"\rSignerService\x12^\n" +
	"\vGenerateKey\x12&.trstctl.signing.v1.GenerateKeyRequest\x1a'.trstctl.signing.v1.GenerateKeyResponse\x12a\n" +
	"\fGetPublicKey\x12'.trstctl.signing.v1.GetPublicKeyRequest\x1a(.trstctl.signing.v1.GetPublicKeyResponse\x12I\n" +
	"\x04Sign\x12\x1f.trstctl.signing.v1.SignRequest\x1a .trstctl.signing.v1.SignResponse\x12[\n" +
	"\n" +
	"DestroyKey\x12%.trstctl.signing.v1.DestroyKeyRequest\x1a&.trstctl.signing.v1.DestroyKeyResponse\x12O\n" +
	"\x06Health\x12!.trstctl.signing.v1.HealthRequest\x1a\".trstctl.signing.v1.HealthResponse\x12d\n" +
	"\rMintSuccessor\x12(.trstctl.signing.v1.MintSuccessorRequest\x1a).trstctl.signing.v1.MintSuccessorResponse\x12[\n" +
	"\n" +
	"GatedIssue\x12%.trstctl.signing.v1.GatedIssueRequest\x1a&.trstctl.signing.v1.GatedIssueResponseB5Z3trstctl.com/trstctl/internal/signing/proto;signerpbb\x06proto3"

var (
	file_internal_signing_proto_signer_proto_rawDescOnce sync.Once
	file_internal_signing_proto_signer_proto_rawDescData []byte
)

func file_internal_signing_proto_signer_proto_rawDescGZIP() []byte {
	file_internal_signing_proto_signer_proto_rawDescOnce.Do(func() {
		file_internal_signing_proto_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_signing_proto_signer_proto_rawDesc), len(file_internal_signing_proto_signer_proto_rawDesc)))
	})
	return file_internal_signing_proto_signer_proto_rawDescData
}

var file_internal_signing_proto_signer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_signing_proto_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_signing_proto_signer_proto_goTypes = []any{
	(Algorithm)(0),                // 0: trstctl.signing.v1.Algorithm
	(Hash)(0),                     // 1: trstctl.signing.v1.Hash
	(RSAPadding)(0),               // 2: trstctl.signing.v1.RSAPadding
	(KeyPurpose)(0),               // 3: trstctl.signing.v1.KeyPurpose
	(HealthResponse_Status)(0),    // 4: trstctl.signing.v1.HealthResponse.Status
	(*KeyHandle)(nil),             // 5: trstctl.signing.v1.KeyHandle
	(*GenerateKeyRequest)(nil),    // 6: trstctl.signing.v1.GenerateKeyRequest
	(*GenerateKeyResponse)(nil),   // 7: trstctl.signing.v1.GenerateKeyResponse
	(*GetPublicKeyRequest)(nil),   // 8: trstctl.signing.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),  // 9: trstctl.signing.v1.GetPublicKeyResponse
	(*SignRequest)(nil),           // 10: trstctl.signing.v1.SignRequest
	(*SignResponse)(nil),          // 11: trstctl.signing.v1.SignResponse
	(*DestroyKeyRequest)(nil),     // 12: trstctl.signing.v1.DestroyKeyRequest
	(*DestroyKeyResponse)(nil),    // 13: trstctl.signing.v1.DestroyKeyResponse
	(*HealthRequest)(nil),         // 14: trstctl.signing.v1.HealthRequest
	(*HealthResponse)(nil),        // 15: trstctl.signing.v1.HealthResponse
	(*MintSuccessorRequest)(nil),  // 16: trstctl.signing.v1.MintSuccessorRequest
	(*MintSuccessorResponse)(nil), // 17: trstctl.signing.v1.MintSuccessorResponse
	(*GatedIssueRequest)(nil),     // 18: trstctl.signing.v1.GatedIssueRequest
	(*GatedIssueResponse)(nil),    // 19: trstctl.signing.v1.GatedIssueResponse
}
var file_internal_signing_proto_signer_proto_depIdxs = []int32{
	0,  // 0: trstctl.signing.v1.GenerateKeyRequest.algorithm:type_name -> trstctl.signing.v1.Algorithm
	3,  // 1: trstctl.signing.v1.GenerateKeyRequest.allowed_purposes:type_name -> trstctl.signing.v1.KeyPurpose
	1,  // 2: trstctl.signing.v1.GenerateKeyRequest.allowed_hashes:type_name -> trstctl.signing.v1.Hash
	5,  // 3: trstctl.signing.v1.GenerateKeyResponse.handle:type_name -> trstctl.signing.v1.KeyHandle
	0,  // 4: trstctl.signing.v1.GenerateKeyResponse.algorithm:type_name -> trstctl.signing.v1.Algorithm
	5,  // 5: trstctl.signing.v1.GetPublicKeyRequest.handle:type_name -> trstctl.signing.v1.KeyHandle
	0,  // 6: trstctl.signing.v1.GetPublicKeyResponse.algorithm:type_name -> trstctl.signing.v1.Algorithm
	5,  // 7: trstctl.signing.v1.SignRequest.handle:type_name -> trstctl.signing.v1.KeyHandle
	1,  // 8: trstctl.signing.v1.SignRequest.hash:type_name -> trstctl.signing.v1.Hash
	2,  // 9: trstctl.signing.v1.SignRequest.rsa_padding:type_name -> trstctl.signing.v1.RSAPadding
	3,  // 10: trstctl.signing.v1.SignRequest.purpose:type_name -> trstctl.signing.v1.KeyPurpose
	5,  // 11: trstctl.signing.v1.DestroyKeyRequest.handle:type_name -> trstctl.signing.v1.KeyHandle
	4,  // 12: trstctl.signing.v1.HealthResponse.status:type_name -> trstctl.signing.v1.HealthResponse.Status
	0,  // 13: trstctl.signing.v1.MintSuccessorRequest.target_algorithm:type_name -> trstctl.signing.v1.Algorithm
	0,  // 14: trstctl.signing.v1.MintSuccessorResponse.successor_algorithm:type_name -> trstctl.signing.v1.Algorithm
	0,  // 15: trstctl.signing.v1.GatedIssueRequest.algorithm:type_name -> trstctl.signing.v1.Algorithm
	6,  // 16: trstctl.signing.v1.SignerService.GenerateKey:input_type -> trstctl.signing.v1.GenerateKeyRequest
	8,  // 17: trstctl.signing.v1.SignerService.GetPublicKey:input_type -> trstctl.signing.v1.GetPublicKeyRequest
	10, // 18: trstctl.signing.v1.SignerService.Sign:input_type -> trstctl.signing.v1.SignRequest
	12, // 19: trstctl.signing.v1.SignerService.DestroyKey:input_type -> trstctl.signing.v1.DestroyKeyRequest
	14, // 20: trstctl.signing.v1.SignerService.Health:input_type -> trstctl.signing.v1.HealthRequest
	16, // 21: trstctl.signing.v1.SignerService.MintSuccessor:input_type -> trstctl.signing.v1.MintSuccessorRequest
	18, // 22: trstctl.signing.v1.SignerService.GatedIssue:input_type -> trstctl.signing.v1.GatedIssueRequest
	7,  // 23: trstctl.signing.v1.SignerService.GenerateKey:output_type -> trstctl.signing.v1.GenerateKeyResponse
	9,  // 24: trstctl.signing.v1.SignerService.GetPublicKey:output_type -> trstctl.signing.v1.GetPublicKeyResponse
	11, // 25: trstctl.signing.v1.SignerService.Sign:output_type -> trstctl.signing.v1.SignResponse
	13, // 26: trstctl.signing.v1.SignerService.DestroyKey:output_type -> trstctl.signing.v1.DestroyKeyResponse
	15, // 27: trstctl.signing.v1.SignerService.Health:output_type -> trstctl.signing.v1.HealthResponse
	17, // 28: trstctl.signing.v1.SignerService.MintSuccessor:output_type -> trstctl.signing.v1.MintSuccessorResponse
	19, // 29: trstctl.signing.v1.SignerService.GatedIssue:output_type -> trstctl.signing.v1.GatedIssueResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_signing_proto_signer_proto_init() }
func file_internal_signing_proto_signer_proto_init() {
	if File_internal_signing_proto_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_signing_proto_signer_proto_rawDesc), len(file_internal_signing_proto_signer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_signing_proto_signer_proto_goTypes,
		DependencyIndexes: file_internal_signing_proto_signer_proto_depIdxs,
		EnumInfos:         file_internal_signing_proto_signer_proto_enumTypes,
		MessageInfos:      file_internal_signing_proto_signer_proto_msgTypes,
	}.Build()
	File_internal_signing_proto_signer_proto = out.File
	file_internal_signing_proto_signer_proto_goTypes = nil
	file_internal_signing_proto_signer_proto_depIdxs = nil
}
