// SPDX-License-Identifier: MPL-2.0

// Command connectorsupportdoc generates the connector support matrix page from
// the census in internal/connector (epic E3).
//
// Generated rather than written, for one reason: a support matrix maintained by
// hand drifts, and it drifts in the optimistic direction. Nobody deletes a row
// when a capability is removed — they delete the code, the test goes with it,
// and the published table keeps promising the thing. Making the page a function
// of the census means the only way to change what is published is to change what
// is true, and -check makes CI fail on the difference.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"trstctl.com/trstctl/internal/ca"
	"trstctl.com/trstctl/internal/connector"
)

const outputPath = "docs/features/connector-support-matrix.md"

// issuerOutputPath is the per-issuer capability disclosure (epic K3).
//
// Generated by the same tool as the connector matrix, and deliberately so: they
// are the same kind of artifact — a published capability claim a buyer verifies
// before a sales call — and two generators would eventually disagree about what
// "supported" means.
const issuerOutputPath = "docs/features/issuer-capability-matrix.md"

func main() {
	check := flag.Bool("check", false, "verify the committed page matches the census instead of rewriting it")
	flag.Parse()

	pages := map[string][]byte{
		outputPath:       render(),
		issuerOutputPath: renderIssuers(),
	}
	if *check {
		for path, want := range pages {
			got, err := os.ReadFile(path) // #nosec G304 -- fixed in-tree doc paths (CWE-22)
			if err != nil {
				fmt.Fprintf(os.Stderr, "capability doc: %v\n", err)
				os.Exit(1)
			}
			if !bytes.Equal(bytes.TrimSpace(got), bytes.TrimSpace(want)) {
				fmt.Fprintf(os.Stderr,
					"capability doc: %s is stale — run `go run ./tools/connectorsupportdoc` and commit\n", path)
				os.Exit(1)
			}
		}
		fmt.Println("capability docs: current")
		return
	}
	for path, want := range pages {
		if err := os.WriteFile(path, want, 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "capability doc: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("capability doc: wrote %s\n", path)
	}
}

func render() []byte {
	var b strings.Builder
	b.WriteString("<!-- Generated by tools/connectorsupportdoc. Do not edit by hand. -->\n\n")
	b.WriteString("# Connector support matrix\n\n")
	b.WriteString("What each appliance connector is **known** to work against.\n\n")
	b.WriteString("This is deliberately not a firmware compatibility table. A version range is a\n")
	b.WriteString("claim about hardware somebody ran, and nothing in this repository runs against a\n")
	b.WriteString("physical or vendor-hosted device. Publishing one would be marketing in the shape\n")
	b.WriteString("of evidence, and you would reasonably plan a migration around it.\n\n")
	b.WriteString("What is published instead is narrower and true: the management API each\n")
	b.WriteString("connector speaks, the operations exercised against a faithful in-process double\n")
	b.WriteString("of that API in CI, and what the family cannot do. Every line below is backed by\n")
	b.WriteString("a test that runs on every change.\n\n")
	b.WriteString("If you are asking \"will this work against our devices\", the honest answer is\n")
	b.WriteString("that we implement the named API contract and exercise these calls against a\n")
	b.WriteString("double of it. Run a dry-run (`connector.test`) against one of your own devices\n")
	b.WriteString("before trusting it with a rotation.\n\n")

	b.WriteString("| Family | API contract | Rollback | Hardware tested |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, row := range connector.SupportMatrix() {
		rollback := "no"
		if connector.CanRollback(row.Family) {
			rollback = "yes (re-bind)"
		}
		hardware := "no"
		if row.HardwareTested {
			hardware = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", row.Family, row.APIContract, rollback, hardware)
	}
	b.WriteString("\n")

	for _, row := range connector.SupportMatrix() {
		fmt.Fprintf(&b, "## %s\n\n", row.Family)
		fmt.Fprintf(&b, "**API contract:** %s\n\n", row.APIContract)
		b.WriteString("**Exercised against a double of that API:**\n\n")
		for _, op := range row.ProvenOperations {
			fmt.Fprintf(&b, "- %s\n", op)
		}
		b.WriteString("\n**Known limits:**\n\n")
		for _, limit := range row.KnownLimits {
			fmt.Fprintf(&b, "- %s\n", limit)
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// renderIssuers builds the per-issuer capability disclosure (epic K3).
//
// The two columns that matter are Issue and "issuance proven", and they are
// deliberately shown side by side. "We implement this authority's API" and "we
// have run an issuance against it" are different claims, and a table that showed
// only the first would say the stronger one everywhere.
func renderIssuers() []byte {
	var b strings.Builder
	b.WriteString("<!-- Generated by tools/connectorsupportdoc. Do not edit by hand. -->\n\n")
	b.WriteString("# Issuer capability matrix\n\n")
	b.WriteString("What this build can do with each certificate authority, per operation.\n\n")
	b.WriteString("Read this before believing a \"CA-agnostic\" claim, including ours. Every row\n")
	b.WriteString("names the test that backs it, and the **Issuance proven** column is separate from\n")
	b.WriteString("**Issue** on purpose: implementing an authority's API and having run an issuance\n")
	b.WriteString("against it are different statements, and only one of them is evidence.\n\n")
	b.WriteString("Today exactly one authority has an end-to-end issuance test. For the rest, the\n")
	b.WriteString("shared HTTP client is exercised (SSRF defaults, endpoint allowlisting, error\n")
	b.WriteString("redaction) and the revoke and unattended-DV columns are checked against the\n")
	b.WriteString("implementations — which is real, and is not the same as an issuance proof.\n\n")

	b.WriteString("| Issuer | Issue | Issuance proven | Renew | Revoke | Unattended DV | Key handling |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, row := range ca.IssuerCapabilityMatrix() {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			row.Issuer, yesNo(row.Issue), provenLabel(row.IssueProven), yesNo(row.Renew),
			yesNo(row.Revoke), yesNo(row.UnattendedDV), row.KeyHandling)
	}
	b.WriteString("\n")

	for _, row := range ca.IssuerCapabilityMatrix() {
		fmt.Fprintf(&b, "## %s\n\n", row.Issuer)
		fmt.Fprintf(&b, "**Backed by:** %s\n\n", row.Evidence)
		if !row.IssueProven {
			b.WriteString("**Issuance is implemented but not proven end to end** against a double of " +
				"this authority's API in CI. Run a test issuance in your own environment before " +
				"depending on it.\n\n")
		}
		if row.RevokeNote != "" {
			fmt.Fprintf(&b, "**Revocation:** %s\n\n", row.RevokeNote)
		}
		if row.UnattendedDVNote != "" {
			fmt.Fprintf(&b, "**Unattended domain validation:** %s\n\n", row.UnattendedDVNote)
		}
	}
	return []byte(b.String())
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

// provenLabel is deliberately wordier than yes/no.
//
// "no" in this column would read as a defect. It is not: it means nobody has run
// the test yet, which is a different and more actionable thing to tell a reader.
func provenLabel(v bool) string {
	if v {
		return "yes"
	}
	return "not tested"
}
