// SPDX-License-Identifier: MPL-2.0

// Command connectorsupportdoc generates the connector support matrix page from
// the census in internal/connector (epic E3).
//
// Generated rather than written, for one reason: a support matrix maintained by
// hand drifts, and it drifts in the optimistic direction. Nobody deletes a row
// when a capability is removed — they delete the code, the test goes with it,
// and the published table keeps promising the thing. Making the page a function
// of the census means the only way to change what is published is to change what
// is true, and -check makes CI fail on the difference.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"trstctl.com/trstctl/internal/connector"
)

const outputPath = "docs/features/connector-support-matrix.md"

func main() {
	check := flag.Bool("check", false, "verify the committed page matches the census instead of rewriting it")
	flag.Parse()

	want := render()
	if *check {
		got, err := os.ReadFile(outputPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "connector support doc: %v\n", err)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(got), bytes.TrimSpace(want)) {
			fmt.Fprintf(os.Stderr,
				"connector support doc: %s is stale — run `go run ./tools/connectorsupportdoc` and commit\n",
				outputPath)
			os.Exit(1)
		}
		fmt.Println("connector support doc: current")
		return
	}
	if err := os.WriteFile(outputPath, want, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "connector support doc: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("connector support doc: wrote %s\n", outputPath)
}

func render() []byte {
	var b strings.Builder
	b.WriteString("<!-- Generated by tools/connectorsupportdoc. Do not edit by hand. -->\n\n")
	b.WriteString("# Connector support matrix\n\n")
	b.WriteString("What each appliance connector is **known** to work against.\n\n")
	b.WriteString("This is deliberately not a firmware compatibility table. A version range is a\n")
	b.WriteString("claim about hardware somebody ran, and nothing in this repository runs against a\n")
	b.WriteString("physical or vendor-hosted device. Publishing one would be marketing in the shape\n")
	b.WriteString("of evidence, and you would reasonably plan a migration around it.\n\n")
	b.WriteString("What is published instead is narrower and true: the management API each\n")
	b.WriteString("connector speaks, the operations exercised against a faithful in-process double\n")
	b.WriteString("of that API in CI, and what the family cannot do. Every line below is backed by\n")
	b.WriteString("a test that runs on every change.\n\n")
	b.WriteString("If you are asking \"will this work against our devices\", the honest answer is\n")
	b.WriteString("that we implement the named API contract and exercise these calls against a\n")
	b.WriteString("double of it. Run a dry-run (`connector.test`) against one of your own devices\n")
	b.WriteString("before trusting it with a rotation.\n\n")

	b.WriteString("| Family | API contract | Rollback | Hardware tested |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, row := range connector.SupportMatrix() {
		rollback := "no"
		if connector.CanRollback(row.Family) {
			rollback = "yes (re-bind)"
		}
		hardware := "no"
		if row.HardwareTested {
			hardware = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", row.Family, row.APIContract, rollback, hardware)
	}
	b.WriteString("\n")

	for _, row := range connector.SupportMatrix() {
		fmt.Fprintf(&b, "## %s\n\n", row.Family)
		fmt.Fprintf(&b, "**API contract:** %s\n\n", row.APIContract)
		b.WriteString("**Exercised against a double of that API:**\n\n")
		for _, op := range row.ProvenOperations {
			fmt.Fprintf(&b, "- %s\n", op)
		}
		b.WriteString("\n**Known limits:**\n\n")
		for _, limit := range row.KnownLimits {
			fmt.Fprintf(&b, "- %s\n", limit)
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}
