// SPDX-License-Identifier: BUSL-1.1

// Command connectorsupportdoc generates the connector support matrix page from
// the census in internal/connector (epic E3).
//
// Generated rather than written, for one reason: a support matrix maintained by
// hand drifts, and it drifts in the optimistic direction. Nobody deletes a row
// when a capability is removed — they delete the code, the test goes with it,
// and the published table keeps promising the thing. Making the page a function
// of the census means the only way to change what is published is to change what
// is true, and -check makes CI fail on the difference.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"trstctl.com/trstctl/internal/ca"
	"trstctl.com/trstctl/internal/connector"
)

const outputPath = "docs/features/connector-support-matrix.md"

// issuerOutputPath is the per-issuer capability disclosure (epic K3).
//
// Generated by the same tool as the connector matrix, and deliberately so: they
// are the same kind of artifact — a published capability claim a buyer verifies
// before a sales call — and two generators would eventually disagree about what
// "supported" means.
const issuerOutputPath = "docs/features/issuer-capability-matrix.md"

func main() {
	check := flag.Bool("check", false, "verify the committed page matches the census instead of rewriting it")
	flag.Parse()

	pages := map[string][]byte{
		outputPath:       render(),
		issuerOutputPath: renderIssuers(),
	}
	if *check {
		for path, want := range pages {
			got, err := os.ReadFile(path) // #nosec G304 -- fixed in-tree doc paths (CWE-22)
			if err != nil {
				fmt.Fprintf(os.Stderr, "capability doc: %v\n", err)
				os.Exit(1)
			}
			if !bytes.Equal(bytes.TrimSpace(got), bytes.TrimSpace(want)) {
				fmt.Fprintf(os.Stderr,
					"capability doc: %s is stale — run `go run ./tools/connectorsupportdoc` and commit\n", path)
				os.Exit(1)
			}
		}
		fmt.Println("capability docs: current")
		return
	}
	for path, want := range pages {
		if err := os.WriteFile(path, want, 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "capability doc: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("capability doc: wrote %s\n", path)
	}
}

func render() []byte {
	var b strings.Builder
	b.WriteString("<!-- Generated by tools/connectorsupportdoc. Do not edit by hand. -->\n\n")
	b.WriteString("# Connector support matrix\n\n")
	b.WriteString("What each connector in E1's accepted thirteen-family scope is **known** to do.\n\n")
	b.WriteString("This is deliberately not a firmware compatibility table. A version range is a\n")
	b.WriteString("claim about hardware somebody ran, and nothing in this repository runs against a\n")
	b.WriteString("physical or vendor-hosted device. Publishing one would be marketing in the shape\n")
	b.WriteString("of evidence, and you would reasonably plan a migration around it.\n\n")
	b.WriteString("What is published instead is narrower and true: the API or local execution\n")
	b.WriteString("contract each connector speaks, the operations exercised by repository tests,\n")
	b.WriteString("and what the family cannot do. Device-API-double evidence is labelled separately\n")
	b.WriteString("from ordinary connector tests. Every line below is backed by a test.\n\n")
	b.WriteString("If you are asking \"will this work against our devices\", the honest answer is\n")
	b.WriteString("that we implement the named contract and exercise the listed calls. Run a dry-run\n")
	b.WriteString("(`connector.test`) against one of your own targets before trusting it with a rotation.\n\n")

	b.WriteString("| Family | API/local contract | E1 disposition | Rollback | External target tested |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, row := range connector.SupportMatrix() {
		rollback := "no"
		if connector.CanRollback(row.Family) {
			rollback = "yes (re-bind)"
		} else if connector.CanRollbackOnHost(row.Family) {
			rollback = "yes (host restore)"
		}
		hardware := "no"
		if row.HardwareTested {
			hardware = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s |\n", row.Family, row.APIContract,
			connector.ParityStatusFor(row.Family).Disposition, rollback, hardware)
	}
	b.WriteString("\n")

	for _, row := range connector.SupportMatrix() {
		fmt.Fprintf(&b, "## %s\n\n", row.Family)
		fmt.Fprintf(&b, "**API/local contract:** %s\n\n", row.APIContract)
		fmt.Fprintf(&b, "**E1 disposition:** `%s`\n\n", connector.ParityStatusFor(row.Family).Disposition)
		if connector.DeviceProven(row.Family) {
			b.WriteString("**Exercised against a faithful management-API double:**\n\n")
		} else {
			b.WriteString("**Exercised by connector tests (not a device-API proof):**\n\n")
		}
		for _, op := range row.ProvenOperations {
			fmt.Fprintf(&b, "- %s\n", op)
		}
		b.WriteString("\n**Known limits:**\n\n")
		for _, limit := range row.KnownLimits {
			fmt.Fprintf(&b, "- %s\n", limit)
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// renderIssuers builds the per-issuer capability disclosure (epic K3).
//
// The two columns that matter are Issue and "issuance proven", and they are
// deliberately shown side by side. "We implement this authority's API" and "we
// have run an issuance against it" are different claims, and a table that showed
// only the first would say the stronger one everywhere.
func renderIssuers() []byte {
	var b strings.Builder
	rows := ca.IssuerCapabilityMatrix()
	proved := 0
	for _, row := range rows {
		if row.IssueProven {
			proved++
		}
	}
	b.WriteString("<!-- Generated by tools/connectorsupportdoc. Do not edit by hand. -->\n\n")
	b.WriteString("# Issuer capability matrix\n\n")
	b.WriteString("What this build can do with each certificate authority, per operation.\n\n")
	b.WriteString("Served state: **Served** through the external-CA API and the same production server assembly tested below.\n\n")
	b.WriteString("Read this before believing a \"CA-agnostic\" claim, including ours. Every row\n")
	b.WriteString("names the test that backs it, and the **Protocol issuance proof** column is separate from\n")
	b.WriteString("**Issue** on purpose: implementing an authority's API and having run an issuance\n")
	b.WriteString("against it are different statements, and only one of them is evidence.\n\n")
	fmt.Fprintf(&b, "This build has high-fidelity protocol issuance proof for %d of %d advertised authorities.\n", proved, len(rows))
	b.WriteString("Each proof starts a separate, nonce-bound authority-protocol substrate, drives the\n")
	b.WriteString("production server assembly through the provider-specific wire exchange, and\n")
	b.WriteString("independently verifies the returned certificate chain. That proves trstctl's\n")
	b.WriteString("adapter and custody path. It is **not live vendor-account certification** and does\n")
	b.WriteString("not prove a customer's policy, entitlement, network, appliance, or service version.\n")
	b.WriteString("Before production, run the same scoped issuance with your configured account.\n\n")

	b.WriteString("| Issuer | Issue | Protocol issuance proof | Renew | Revoke | Unattended DV | Key handling |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			row.Issuer, yesNo(row.Issue), provenLabel(row.IssueProven), yesNo(row.Renew),
			yesNo(row.Revoke), yesNo(row.UnattendedDV), row.KeyHandling)
	}
	b.WriteString("\n")

	for _, row := range rows {
		fmt.Fprintf(&b, "## %s\n\n", row.Issuer)
		fmt.Fprintf(&b, "**Backed by:** %s\n\n", row.Evidence)
		if row.IssueProven {
			b.WriteString("**Protocol issuance proof:** the universal DoD test drives this driver through its " +
				"high-fidelity authority-protocol substrate and independently verifies the returned chain. " +
				"This does not replace a scoped test against your real vendor account.\n\n")
		} else {
			b.WriteString("**Issuance is implemented but not proven end to end** against a double of " +
				"this authority's API in CI. Run a test issuance in your own environment before " +
				"depending on it.\n\n")
		}
		if row.RevokeNote != "" {
			fmt.Fprintf(&b, "**Revocation:** %s\n\n", row.RevokeNote)
		}
		if row.UnattendedDVNote != "" {
			fmt.Fprintf(&b, "**Unattended domain validation:** %s\n\n", row.UnattendedDVNote)
		}
	}
	return []byte(b.String())
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

// provenLabel is deliberately wordier than yes/no.
//
// "no" in this column would read as a defect. It is not: it means nobody has run
// the test yet, which is a different and more actionable thing to tell a reader.
func provenLabel(v bool) string {
	if v {
		return "yes"
	}
	return "not tested"
}
