// SPDX-License-Identifier: LicenseRef-trstctl-EE

// Workload-agent predecessor co-sign contract (PCAS claim 19, INT-16). The platform
// signer/orchestrator forms a succession commitment and asks the workload agent —
// which holds the predecessor key — to co-sign it. The request carries the STRUCTURED
// commitment fields (a canonical, reversible encoding), NEVER an opaque digest, so the
// agent reconstructs and domain-separates the commitment itself and can never be used
// as a generic signing oracle (FIG. 5 oracle-prevention). Only the predecessor
// signature — public material — crosses back.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ee/succession/agent/cosignpb/cosign.proto

package cosignpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoSignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// purpose is the distinct key-usage purpose; a request under any other purpose is
	// refused so the agent cannot be repurposed as a generic signing oracle.
	Purpose string `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// fields is the canonical, reversible encoding of the succession commitment fields
	// (agent.MarshalFields). It is NOT a digest: the agent decodes it into typed,
	// inspectable fields, validates them against its own binding, and reconstructs the
	// domain-separated commitment itself before signing.
	Fields        []byte `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoSignRequest) Reset() {
	*x = CoSignRequest{}
	mi := &file_ee_succession_agent_cosignpb_cosign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoSignRequest) ProtoMessage() {}

func (x *CoSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ee_succession_agent_cosignpb_cosign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoSignRequest.ProtoReflect.Descriptor instead.
func (*CoSignRequest) Descriptor() ([]byte, []int) {
	return file_ee_succession_agent_cosignpb_cosign_proto_rawDescGZIP(), []int{0}
}

func (x *CoSignRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CoSignRequest) GetFields() []byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CoSignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature is the predecessor co-signature over the agent-reconstructed
	// commitment. Only this public material crosses back; the predecessor key never
	// leaves the agent.
	Signature     []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoSignResponse) Reset() {
	*x = CoSignResponse{}
	mi := &file_ee_succession_agent_cosignpb_cosign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoSignResponse) ProtoMessage() {}

func (x *CoSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ee_succession_agent_cosignpb_cosign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoSignResponse.ProtoReflect.Descriptor instead.
func (*CoSignResponse) Descriptor() ([]byte, []int) {
	return file_ee_succession_agent_cosignpb_cosign_proto_rawDescGZIP(), []int{1}
}

func (x *CoSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_ee_succession_agent_cosignpb_cosign_proto protoreflect.FileDescriptor

const file_ee_succession_agent_cosignpb_cosign_proto_rawDesc = "" +
	"\n" +
	")ee/succession/agent/cosignpb/cosign.proto\x12\x15trstctl.pcas.agent.v1\"A\n" +
	"\rCoSignRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x16\n" +
	"\x06fields\x18\x02 \x01(\fR\x06fields\".\n" +
	"\x0eCoSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature2h\n" +
	"\x0fCoSignerService\x12U\n" +
	"\x06CoSign\x12$.trstctl.pcas.agent.v1.CoSignRequest\x1a%.trstctl.pcas.agent.v1.CoSignResponseB2Z0trstctl.com/trstctl/ee/succession/agent/cosignpbb\x06proto3"

var (
	file_ee_succession_agent_cosignpb_cosign_proto_rawDescOnce sync.Once
	file_ee_succession_agent_cosignpb_cosign_proto_rawDescData []byte
)

func file_ee_succession_agent_cosignpb_cosign_proto_rawDescGZIP() []byte {
	file_ee_succession_agent_cosignpb_cosign_proto_rawDescOnce.Do(func() {
		file_ee_succession_agent_cosignpb_cosign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ee_succession_agent_cosignpb_cosign_proto_rawDesc), len(file_ee_succession_agent_cosignpb_cosign_proto_rawDesc)))
	})
	return file_ee_succession_agent_cosignpb_cosign_proto_rawDescData
}

var file_ee_succession_agent_cosignpb_cosign_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ee_succession_agent_cosignpb_cosign_proto_goTypes = []any{
	(*CoSignRequest)(nil),  // 0: trstctl.pcas.agent.v1.CoSignRequest
	(*CoSignResponse)(nil), // 1: trstctl.pcas.agent.v1.CoSignResponse
}
var file_ee_succession_agent_cosignpb_cosign_proto_depIdxs = []int32{
	0, // 0: trstctl.pcas.agent.v1.CoSignerService.CoSign:input_type -> trstctl.pcas.agent.v1.CoSignRequest
	1, // 1: trstctl.pcas.agent.v1.CoSignerService.CoSign:output_type -> trstctl.pcas.agent.v1.CoSignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ee_succession_agent_cosignpb_cosign_proto_init() }
func file_ee_succession_agent_cosignpb_cosign_proto_init() {
	if File_ee_succession_agent_cosignpb_cosign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ee_succession_agent_cosignpb_cosign_proto_rawDesc), len(file_ee_succession_agent_cosignpb_cosign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ee_succession_agent_cosignpb_cosign_proto_goTypes,
		DependencyIndexes: file_ee_succession_agent_cosignpb_cosign_proto_depIdxs,
		MessageInfos:      file_ee_succession_agent_cosignpb_cosign_proto_msgTypes,
	}.Build()
	File_ee_succession_agent_cosignpb_cosign_proto = out.File
	file_ee_succession_agent_cosignpb_cosign_proto_goTypes = nil
	file_ee_succession_agent_cosignpb_cosign_proto_depIdxs = nil
}
