// Code generated by web/scripts/extract-i18n-messages.mjs.
// DO NOT EDIT by hand. Regenerate with: npm run i18n:extract
//
// This catalog captures user-facing source literals that have not yet moved
// to typed runtime message keys. The --check mode blocks new hard-coded UI
// copy unless the catalog is intentionally regenerated.

export const extractedMessages = [

] as const;

export type ExtractedMessageKey = (typeof extractedMessages)[number]["key"];
