export type ApiWorkflowCoverageKind = "console-flow" | "api-explorer" | "api-cli-exception";

export interface ApiWorkflowCoverage {
  path: string;
  route: string;
  owner: string;
  kind: ApiWorkflowCoverageKind;
  workflow: string;
  rationale: string;
}

export const apiWorkflowCoverage = [
  {
    path: "/api/v1/identities/{id}/deployment-evidence",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Exact certificate validity from completed deployment evidence",
    rationale:
      "Identity detail shows the last completed deployment or restore, its exact certificate dates and status, and the historical proof boundary with a link to the exact certificate's revocation view.",
  },
  {
    path: "/api/v1/access/sessions",
    route: "/admin/access",
    owner: "SURFACE/access",
    kind: "console-flow",
    workflow: "Privileged access session ledger",
    rationale:
      "The Platform access administration area lists JIT privileged access sessions with status, target, expiry, per-session detail, and an open-session workflow.",
  },
  {
    path: "/api/v1/access/sessions/{id}",
    route: "/admin/access",
    owner: "SURFACE/access",
    kind: "console-flow",
    workflow: "Privileged access session detail",
    rationale:
      "Each session row on the Platform page opens a detail dialog with attestation, audit, and target transcripts rendered from the served session record.",
  },
  {
    path: "/api/v1/agents/{id}/cert-revocations",
    route: "/agents",
    owner: "SURFACE/agents",
    kind: "console-flow",
    workflow: "Agent mTLS certificate revocation",
    rationale:
      "The Agents page has a per-agent revoke-certificate action with RFC 5280 reason selection, optional serial/fingerprint, and a guarded confirmation dialog.",
  },
  {
    path: "/api/v1/ca/authorities",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "CA hierarchy inventory",
    rationale:
      "The CA Hierarchy page shows authority inventory, managed status, issuer visibility, and CA discovery evidence with loading, empty, and error states.",
  },
  {
    path: "/api/v1/ca/authorities/intermediates",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Signer-backed intermediate CA creation",
    rationale: "The CA Hierarchy page creates signer-backed intermediates through a ceremony-gated dialog with parent selection and validated spec input.",
  },
  {
    path: "/api/v1/ca/authorities/roots",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Signer-backed root CA creation",
    rationale: "The CA Hierarchy page creates signer-backed roots through a ceremony-gated dialog binding the quorum-approved ceremony id to the create call.",
  },
  {
    path: "/api/v1/ca/authorities/{id}/intermediates/csr",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Issue intermediate CA from CSR",
    rationale: "Each served authority row offers a sign-intermediate-CSR dialog with ceremony id, CSR validation, and an in-dialog issued-certificate result.",
  },
  {
    path: "/api/v1/ca/authorities/{id}/issue",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Issue leaf certificate from CA authority",
    rationale: "Each served authority row offers an issue-leaf dialog with CSR validation and TTL, returning serial, expiry, and PEM with a copy affordance.",
  },
  {
    path: "/api/v1/ca/authorities/{id}/rekey",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Signer-backed CA renewal and re-key",
    rationale:
      "The CA Hierarchy page starts the m-of-n re-key ceremony, submits the activation request, and displays the stable predecessor and active successor issue URLs.",
  },
  {
    path: "/api/v1/ca/ceremonies/{id}",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "CA ceremony detail lookup",
    rationale: "Ceremony rows on the CA Hierarchy page open a detail dialog showing approval progress against threshold, status, purpose, and opener.",
  },
  {
    path: "/api/v1/certificates/bulk-revoke",
    route: "/certificates",
    owner: "SURFACE/certificates",
    kind: "console-flow",
    workflow: "Transactional certificate bulk revoke",
    rationale:
      "The Certificates inventory has row selection with a guarded bulk-revoke dialog that sends one transactional request and reports revoked/skipped/failed totals.",
  },
  {
    path: "/api/v1/certificates/{id}",
    route: "/certificates",
    owner: "SURFACE/certificates",
    kind: "console-flow",
    workflow: "Certificate detail drawer",
    rationale: "The Certificates page opens a detail drawer via getCertificate with loading, permission, error, and populated states.",
  },
  {
    path: "/api/v1/connectors/catalog",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector registry",
    rationale: "The Connectors page loads the connector catalog and shows empty/error states with target setup and action workflows.",
  },
  {
    path: "/api/v1/connectors/deliveries",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector delivery receipt list",
    rationale: "The Connectors and Operations pages show recent delivery receipts, attempts, rollback references, and empty/error states.",
  },
  {
    path: "/api/v1/connectors/deliveries/{id}",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector delivery receipt detail",
    rationale:
      "Delivery receipt rows on the Connectors page open a detail dialog rendering the full receipt including rollback reference, reason, and idempotency key.",
  },
  {
    path: "/api/v1/connectors/outbox-circuits",
    route: "/connectors",
    owner: "SURFACE/runops",
    kind: "console-flow",
    workflow: "Outbox circuit breaker diagnostics",
    rationale: "The Connectors page shows outbox destination circuit state beside delivery receipts with tone-coded status and failure detail.",
  },
  {
    path: "/api/v1/connectors/targets/{id}",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector target actions",
    rationale: "The Connectors page lists targets and drives bind, test, deploy, and rollback actions against selected targets.",
  },
  {
    path: "/api/v1/discovery/findings",
    route: "/discovery",
    owner: "SURFACE/discovery",
    kind: "console-flow",
    workflow: "Discovery finding triage",
    rationale: "The Discovery page lists findings and owns claim/dismiss triage with loading, empty, and error states.",
  },
  {
    path: "/api/v1/ephemeral",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Attestation-gated ephemeral credential request",
    rationale:
      "The Secrets ephemeral section requests attestation-gated JIT credentials and renders awaiting-approval progress or the issued certificate inline.",
  },
  {
    path: "/api/v1/ephemeral/{id}/approvals",
    route: "/approvals",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Ephemeral credential approval",
    rationale: "The Approvals page has an ephemeral-credential approval card that issues a pending request by id and reports approver and quorum progress.",
  },
  {
    path: "/api/v1/external-cas/{id}/issue",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "External CA issuance path discovery",
    rationale: "The CA Hierarchy page surfaces external CA discovery rows and their served issuance paths; direct issue remains an advanced operator action.",
  },
  {
    path: "/api/v1/identities/bulk-revoke",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Transactional identity bulk revoke",
    rationale: "The Identities bulk action now sends one transactional bulk-revoke request with reason selection and a server-computed result summary.",
  },
  {
    path: "/api/v1/identities/{id}",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Identity detail and lifecycle drawer",
    rationale: "The Identities page opens lifecycle detail, delivery evidence, and approval context for selected identities.",
  },
  {
    path: "/api/v1/identities/{id}/transitions",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Identity lifecycle transition",
    rationale: "The Identities page drives issue, deploy, renew, revoke, and retire transitions with destructive confirmation and error states.",
  },
  {
    path: "/api/v1/issuers/{id}",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "Issuer detail visibility",
    rationale:
      "The CA Hierarchy issuer table renders each issuer's kind, internal flag, chain, and public key; the typed client also exposes issuer lookup by id.",
  },
  {
    path: "/api/v1/lifecycle/rotation-runs",
    route: "/operations",
    owner: "SURFACE/lifecycle",
    kind: "console-flow",
    workflow: "Rotation run queue",
    rationale: "The Operations, Dashboard, Identities, and Certificates pages show rotation runs and empty/error states.",
  },
  {
    path: "/api/v1/lifecycle/rotation-runs/{id}",
    route: "/operations",
    owner: "SURFACE/lifecycle",
    kind: "console-flow",
    workflow: "Rotation run detail lookup",
    rationale: "Rotation run rows on the Operations page open a detail dialog with fingerprints, trigger, rollback reference, and failure detail.",
  },
  {
    path: "/api/v1/notifications/{id}",
    route: "/notifications",
    owner: "SURFACE/notifications",
    kind: "console-flow",
    workflow: "Notification inbox row",
    rationale: "The Notifications page lists rows and drives read/requeue actions with loading, empty, and error states.",
  },
  {
    path: "/api/v1/owners/{id}",
    route: "/owners",
    owner: "SURFACE/owners",
    kind: "console-flow",
    workflow: "Owner detail/update/delete",
    rationale: "The Owners page has per-row edit and delete actions with a pre-filled form dialog and a typed-name destructive confirmation.",
  },
  {
    path: "/api/v1/privacy/subject-exports",
    route: "/integrate/api",
    owner: "SURFACE/privacy",
    kind: "api-explorer",
    workflow: "Privacy subject export",
    rationale: "The Privacy page covers catalog, erasure, and retention; subject portability exports are available through the API playground.",
  },
  {
    path: "/api/v1/remediation/playbook-runs",
    route: "/incidents",
    owner: "SURFACE/incidents",
    kind: "console-flow",
    workflow: "Remediation playbook run history",
    rationale: "The Incidents page runs playbooks and displays recent playbook run evidence, including empty/error states.",
  },
  {
    path: "/api/v1/secrets/rotations",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Worker-queued connector secret rotation",
    rationale:
      "The Secrets rotation section accepts only connector:<target>, queues the durable delivery command, and renders queued plus old-to-new reference evidence; static and dynamic providers fail closed before effects.",
  },
  {
    path: "/api/v1/secrets/scans/repositories",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Repository secret scanning posture",
    rationale: "The Secrets page displays repository scanning posture, provider webhook paths, and empty/error states.",
  },
  {
    path: "/api/v1/secrets/scans/third-party",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Third-party secret scanning posture",
    rationale: "The Secrets page displays third-party artifact scanning posture and can ingest configured provider artifacts.",
  },
  {
    path: "/api/v1/secrets/rotation-schedules",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Scheduled secret rotation management",
    rationale: "The Secrets rotation section lists zero-downtime rotation schedules and creates new schedules through a validated dialog.",
  },
  {
    path: "/api/v1/secrets/rotation-schedules/run-due",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Run due secret rotations",
    rationale: "The Secrets rotation section runs all due schedules on demand and reports how many rotations ran with per-run outcomes.",
  },
  {
    path: "/api/v1/privacy/archive-erasure-attestations",
    route: "/privacy",
    owner: "SURFACE/privacy",
    kind: "console-flow",
    workflow: "Archive erasure evidence",
    rationale: "The Privacy page lists backup and archive erasure attestations with subject filtering and records new attestations through a guided dialog.",
  },
  {
    path: "/api/v1/remediation/owner-actions",
    route: "/incidents",
    owner: "SURFACE/incidents",
    kind: "console-flow",
    workflow: "Owner remediation queue",
    rationale: "The Incidents remediation evidence section renders the owner-driven self-remediation queue with severity, scope, and rollback references.",
  },
  {
    path: "/api/v1/platform/distribution",
    route: "/admin/editions",
    owner: "SURFACE/platform",
    kind: "console-flow",
    workflow: "Distribution posture disclosure",
    rationale: "The Platform page shows the run-anywhere distribution posture: production mode, lineage, run modes, host archives, and air-gap readiness.",
  },
  {
    path: "/api/v1/pqc/campaigns",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "Core PQC migration campaign inventory and creation",
    rationale:
      "The Posture page lists tenant-scoped migration campaigns and creates campaigns over selected CBOM findings with owner, deadline, and wave controls.",
  },
  {
    path: "/api/v1/pqc/campaigns/{id}",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "Core PQC migration campaign detail and update",
    rationale:
      "Selecting a campaign on the Posture page loads its findings, evidence state, and Community-safe edition disclosure while the typed client exposes its update path.",
  },
  {
    path: "/api/v1/pqc/campaigns/{id}/readiness",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "PQC migration readiness evidence",
    rationale:
      "The selected campaign workflow records operator readiness gates and their evidence digest without requiring the licensed fleet execution engine.",
  },
  {
    path: "/api/v1/pqc/campaigns/{id}/findings/{finding_id}/disposition",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "PQC finding migration disposition",
    rationale:
      "Operators can record manual or third-party remediation of an individual CBOM finding, including method and evidence digest, from the campaign detail.",
  },
  {
    path: "/api/v1/pqc/campaigns/{id}/close",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "PQC migration campaign closure",
    rationale:
      "The Posture workflow gates closure on readiness and finding dispositions, requires explicit confirmation, and surfaces mutation failures in place.",
  },
  {
    path: "/api/v1/pqc/campaigns/{id}/evidence",
    route: "/posture",
    owner: "SURFACE/posture",
    kind: "console-flow",
    workflow: "Signed PQC migration closure evidence",
    rationale:
      "A closed campaign exposes its signed closure evidence and verification key for operator inspection and download from the reachable Posture page.",
  },
  {
    path: "/api/v1/acme/dns-01/preflight",
    route: "/protocols",
    owner: "SURFACE/protocols",
    kind: "console-flow",
    workflow: "DNS-01 preflight validation",
    rationale: "Each DNS-01 provider config row offers a preflight dialog validating propagation, CNAME, CAA, method, and wildcard policy before enrollment.",
  },
  {
    path: "/api/v1/acme/dns-01/provider-configs/{id}",
    route: "/protocols",
    owner: "SURFACE/protocols",
    kind: "console-flow",
    workflow: "DNS-01 provider config administration",
    rationale: "DNS-01 provider config rows on the Protocols page support pre-filled edit and typed-name delete dialogs over the served config record.",
  },
  {
    path: "/api/v1/mdm/scep/policies/{id}",
    route: "/protocols",
    owner: "SURFACE/protocols",
    kind: "console-flow",
    workflow: "SCEP policy administration",
    rationale: "SCEP policy rows on the Protocols page support pre-filled edit and typed-name delete dialogs covering the full policy request surface.",
  },
  {
    path: "/api/v1/mdm/scep/policies/{id}/rotate-challenge",
    route: "/protocols",
    owner: "SURFACE/protocols",
    kind: "console-flow",
    workflow: "SCEP challenge rotation evidence",
    rationale: "SCEP policy rows offer a rotate-challenge action that records rotation evidence and surfaces the new rotation version.",
  },
] as const satisfies readonly ApiWorkflowCoverage[];
