/**
 * Browser-only sample responses for the isolated evaluation build.
 *
 * This module is loaded through a compile-time-guarded dynamic import in
 * api.ts. The normal embedded product build compiles that branch away, while
 * Vite dev and VITE_TRSTCTL_DEMO=1 builds include it. Values are read-model
 * responses only: a method absent from this catalog remains fail-closed.
 */
import { translateNow } from "@/i18n/I18nProvider";

export interface PreviewReadResult {
  matched: boolean;
  value?: unknown;
}

const generatedAt = "2026-07-27T08:00:00Z";
const tenantID = "preview-tenant";

const certificates = [
  {
    id: "certificate-preview-api",
    tenant_id: tenantID,
    subject: "api.preview-lab.example",
    sans: ["api.preview-lab.example", "payments.preview-lab.example"],
    fingerprint: "sha256:preview-api-4f01",
    serial: "01A9",
    issuer: "Preview Lab Intermediate CA",
    owner_id: "owner-platform",
    source: "internal-ca",
    deployment_location: "edge/production/api",
    key_algorithm: "RSA-2048",
    not_before: "2026-07-01T00:00:00Z",
    not_after: "2030-08-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    status: "active",
  },
  {
    id: "certificate-preview-mesh",
    tenant_id: tenantID,
    subject: "spiffe://preview-lab.example/ns/payments/sa/api",
    sans: ["spiffe://preview-lab.example/ns/payments/sa/api"],
    fingerprint: "sha256:preview-mesh-8c12",
    serial: "01AA",
    issuer: "Preview Lab Workload CA",
    owner_id: "owner-payments",
    source: "spiffe",
    deployment_location: "kubernetes/payments/api",
    key_algorithm: "ML-DSA-65",
    not_before: "2026-07-27T07:45:00Z",
    not_after: "2030-07-27T08:15:00Z",
    created_at: "2026-07-27T07:45:00Z",
    status: "active",
  },
  {
    id: "certificate-preview-legacy",
    tenant_id: tenantID,
    subject: "legacy-gateway.preview-lab.example",
    sans: ["legacy-gateway.preview-lab.example"],
    fingerprint: "sha256:preview-legacy-2bd7",
    serial: "0198",
    issuer: "Imported Partner CA",
    source: "network-discovery",
    deployment_location: "datacenter/gateway-04",
    key_algorithm: "RSA-2048",
    not_before: "2024-08-01T00:00:00Z",
    not_after: "2030-07-31T00:00:00Z",
    created_at: "2026-07-26T11:20:00Z",
    status: "active",
  },
];

const identities = [
  {
    id: "identity-preview-api",
    tenant_id: tenantID,
    kind: "x509_certificate",
    name: "payments API TLS",
    owner_id: "owner-payments",
    issuer_id: "issuer-preview-intermediate",
    status: "deployed",
    not_before: "2026-07-01T00:00:00Z",
    not_after: "2030-08-01T00:00:00Z",
  },
  {
    id: "identity-preview-workload",
    tenant_id: tenantID,
    kind: "workload_identity",
    name: "payments workload SVID",
    owner_id: "owner-payments",
    issuer_id: "issuer-preview-intermediate",
    status: "issued",
    not_before: "2026-07-27T07:45:00Z",
    not_after: "2030-07-27T08:15:00Z",
  },
  {
    id: "identity-preview-secret",
    tenant_id: tenantID,
    kind: "secret",
    name: "payments database credential",
    owner_id: "owner-payments",
    status: "issued",
  },
];

const risks = [
  {
    credential_id: "certificate-preview-api",
    subject: "api.preview-lab.example",
    kind: "x509_certificate",
    score: 94,
    expires_at: "2030-08-01T00:00:00Z",
    owner_active: true,
    privilege: 3,
    sensitivity: 3,
    exposure: 3,
    components: { age: 12, rotation: 18, privilege: 20, exposure: 20, owner: 4, sensitivity: 20 },
  },
  {
    credential_id: "identity-preview-secret",
    subject: "payments/production/database",
    kind: "secret",
    score: 81,
    expires_at: "2030-09-01T00:00:00Z",
    owner_active: true,
    privilege: 3,
    sensitivity: 3,
    exposure: 1,
    components: { age: 18, rotation: 19, privilege: 20, exposure: 7, owner: 2, sensitivity: 15 },
  },
  {
    credential_id: "certificate-preview-legacy",
    subject: "legacy-gateway.preview-lab.example",
    kind: "x509_certificate",
    score: 76,
    expires_at: "2030-07-31T00:00:00Z",
    owner_active: false,
    privilege: 2,
    sensitivity: 2,
    exposure: 3,
    components: { age: 20, rotation: 18, privilege: 10, exposure: 18, owner: 8, sensitivity: 2 },
  },
];

const inventoryItems = [
  {
    id: "inventory-preview-api",
    tenant_id: tenantID,
    display_name: "payments API TLS",
    kind: "x509_certificate",
    source: "certificate_inventory",
    status: "active",
    owner_id: "owner-payments",
    fingerprint: "sha256:preview-api-4f01",
    ref: "certificate:certificate-preview-api",
    risk_score: 94,
    created_at: "2026-07-01T00:00:00Z",
    discovered_at: "2026-07-27T07:30:00Z",
    not_after: "2030-08-01T00:00:00Z",
    metadata: { environment: "production", region: "us-east-1" },
  },
  {
    id: "inventory-preview-secret",
    tenant_id: tenantID,
    display_name: "payments database credential",
    kind: "secret",
    source: "native_secret_store",
    status: "active",
    owner_id: "owner-payments",
    ref: "secret:payments/production/database",
    risk_score: 81,
    created_at: "2026-05-12T09:00:00Z",
    metadata: { engine: "native", version: 7 },
  },
  {
    id: "inventory-preview-ssh",
    tenant_id: tenantID,
    display_name: "bastion deploy key",
    kind: "ssh_key",
    source: "ssh_discovery",
    status: "unmanaged",
    ref: "ssh:bastion.preview-lab.example/deploy",
    risk_score: 72,
    created_at: "2025-02-11T12:00:00Z",
    metadata: { host: "bastion.preview-lab.example" },
  },
];

const impact = {
  node: { id: "identity-preview-api", kind: "credential", name: "payments API TLS" },
  affected: [
    { id: "workload-preview-payments", kind: "workload", name: "payments service" },
    { id: "resource-preview-ledger", kind: "resource", name: "ledger database" },
  ],
  by_kind: { workload: 1, resource: 1 },
};

const incidentExecution = {
  id: "incident-preview-001",
  tenant_id: tenantID,
  compromised_identity_id: "identity-preview-api",
  replacement_identity_id: "identity-preview-api-next",
  connector_delivery_id: "delivery-preview-001",
  status: "running",
  phase: "replacement_deployed",
  reason: "Sample drill: suspected private-key exposure",
  blast_radius: impact,
  revocation_status: "revocation_queued",
  evidence_bundle_format: "jws",
  evidence_bundle: "preview-evidence://incident-preview-001",
  failed_targets: [],
  rollback_refs: ["deployment:payments-api/previous"],
  idempotency_key: "preview-idempotency-incident-001",
  created_by: "preview-incident-commander",
  created_at: "2026-07-27T07:20:00Z",
  updated_at: "2026-07-27T07:54:00Z",
};

const ownerQueue = {
  capability: "owner_self_remediation",
  generated_at: generatedAt,
  status: "ready",
  evidence_refs: ["preview-evidence://owner-remediation"],
  summary: { total: 1, open: 1, accepted: 0, critical: 0, high: 1, medium: 0, low: 0 },
  items: [
    {
      id: "owner-action-preview-001",
      inventory_id: "inventory-preview-secret",
      target_identity_id: "identity-preview-secret",
      display_name: "Reduce unused database scopes",
      kind: "secret",
      owner_id: "owner-payments",
      owner_name: "Payments Platform",
      owner_email: "payments@example.invalid",
      playbook_id: "nhi-right-size",
      action: "right_size",
      reason: "Three granted scopes were unused for 90 days",
      recommendation: "Remove admin and schema-owner scopes after owner review.",
      remove_scopes: ["database:admin", "schema:owner"],
      recommended_scopes: ["database:connect"],
      risk_score: 81,
      severity: "high",
      source: "risk_projection",
      status: "open",
      connector: "postgresql",
      target: "ledger-primary",
      rollback_ref: "preview-evidence://rollback/owner-action-preview-001",
      evidence_refs: ["preview-evidence://risk/identity-preview-secret"],
    },
  ],
};

const emptyRiskSummary = {
  critical: 0,
  high: 0,
  medium: 0,
  low: 0,
  total_analyzed: 3,
};

const previewReaders: Record<string, () => unknown> = {
  certificates: () => certificates,
  certificatePage: () => ({ items: certificates }),
  certificateHealth: () => ({
    generated_at: generatedAt,
    inventory_path: "/api/v1/certificates",
    expiring_path: "/api/v1/certificates?expiring_before=2030-08-26T00:00:00Z",
    summary: {
      total: 3,
      active: 3,
      revoked: 0,
      superseded: 0,
      expired: 0,
      expiring_7d: 0,
      expiring_30d: 0,
      expiring_90d: 0,
      unknown_expiry_count: 0,
      external_source_count: 1,
      imported_count: 1,
      discovered_count: 1,
      health: "warning",
    },
    expiry_buckets: [
      { name: "later", count: 3 },
      { name: "unknown", count: 0 },
    ],
    source_breakdown: [
      { source: "internal-ca", count: 2, expired: 0, expiring_30d: 0, external: false },
      { source: "network-discovery", count: 1, expired: 0, expiring_30d: 0, external: true },
    ],
    expiring: [],
  }),
  crlDistributions: () => ({ items: [] }),
  rogueCertificates: () => ({
    capability: "rogue_certificate_posture",
    coverage: ["certificate_inventory", "ct_monitoring"],
    evidence_refs: ["preview-evidence://rogue-certificate-posture"],
    generated_at: generatedAt,
    recommended_actions: ["Assign an owner and replace the discovered legacy gateway certificate."],
    summary: {
      total_analyzed: 3,
      findings: 1,
      rogue: 1,
      non_compliant: 0,
      critical: 0,
      high: 1,
      medium: 0,
      low: 0,
      ct_unexpected: 0,
      expired_active: 0,
      issuer_missing: 0,
      lifetime_violations: 0,
      owner_missing: 1,
      recommendations: 1,
      weak_key: 1,
    },
    findings: [],
  }),
  owners: () => [
    { id: "owner-payments", tenant_id: tenantID, kind: "team", name: "Payments Platform", email: "payments@example.invalid" },
    { id: "owner-platform", tenant_id: tenantID, kind: "team", name: "Core Platform", email: "platform@example.invalid" },
  ],
  identities: () => identities,
  identityPage: () => ({ items: identities, next_cursor: "" }),
  nhiInventory: () => ({
    generated_at: generatedAt,
    items: inventoryItems,
    summary: { x509_certificate: 1, secret: 1, ssh_key: 1, agent: 2 },
    coverage: ["certificate_inventory", "native_secret_store", "ssh_discovery"],
  }),
  risk: () => risks,
  contextualRiskPriorities: () => ({
    capability: "contextual_risk_priorities",
    generated_at: generatedAt,
    coverage: ["credentials", "graph", "owners"],
    summary: {
      ...emptyRiskSummary,
      critical: 1,
      high: 2,
      priorities: 3,
      recommendations: 3,
      high_blast_radius: 1,
      near_expiry: 0,
      orphaned: 1,
      weak_crypto_context: 2,
    },
    urgent_summary: {
      status: "complete",
      scope: "All served credential-risk and contextual-priority projections for this tenant; totals deduplicate credential_id.",
      included_projections: ["credential_risk_scores", "contextual_priorities"],
      unique_analyzed: 3,
      urgent: 3,
      critical: 1,
      high: 2,
      credential_risk: { analyzed: 3, critical: 1, high: 2 },
      contextual_priorities: { analyzed: 3, critical: 1, high: 2 },
    },
    priorities: [
      {
        rank: 1,
        credential_id: "certificate-preview-api",
        subject: "api.preview-lab.example",
        kind: "x509_certificate",
        base_score: 94,
        contextual_score: 97,
        severity: "critical",
        privilege: 3,
        sensitivity: 3,
        owner_active: true,
        expires_at: "2030-08-01T00:00:00Z",
        blast_radius: 2,
        credential_blast_radius: 0,
        workload_blast_radius: 1,
        resource_blast_radius: 1,
        crypto_asset_blast_radius: 0,
        weak_crypto_context: 1,
        components: risks[0]!.components,
        priority_reasons: ["internet exposed", "production payment path"],
        recommended_action: "Rotate the certificate and validate downstream deployment.",
        evidence_refs: ["preview-evidence://risk/certificate-preview-api"],
      },
    ],
  }),
  nhiOverPrivilegePosture: () => ({
    capability: "nhi_overprivilege_posture",
    coverage: ["native_secret_store"],
    generated_at: generatedAt,
    findings: [],
    summary: { ...emptyRiskSummary, overprivileged: 1, unused_grants: 2, wildcard_grants: 0, least_privilege_plans: 1 },
  }),
  nhiPolicyCompliance: () => ({
    capability: "nhi_policy_compliance",
    coverage: ["credential_inventory"],
    evidence_refs: ["preview-evidence://policy-compliance"],
    generated_at: generatedAt,
    findings: [],
    recommended_actions: ["Replace the ownerless legacy gateway certificate."],
    summary: {
      ...emptyRiskSummary,
      compliant: 2,
      violations: 1,
      business_purpose_missing: 0,
      expiry_violations: 0,
      geo_violations: 0,
      rotation_violations: 1,
      scope_violations: 0,
    },
  }),
  nhiStalePosture: () => ({
    capability: "nhi_stale_posture",
    coverage: ["credential_inventory"],
    generated_at: generatedAt,
    findings: [],
    thresholds: { dormant_activity_days: 30, stale_activity_days: 90, unused_no_activity_days: 14 },
    summary: {
      ...emptyRiskSummary,
      findings: 1,
      dormant: 0,
      orphaned: 1,
      recommendations: 1,
      stale: 1,
      unused: 0,
    },
  }),
  nhiStaticPosture: () => ({
    capability: "nhi_static_posture",
    coverage: ["credential_inventory"],
    generated_at: generatedAt,
    findings: [],
    thresholds: { long_lived_credential_days: 90, no_expiry_minimum_age_days: 30, rotation_overdue_days: 60 },
    summary: {
      ...emptyRiskSummary,
      findings: 1,
      long_lived: 1,
      no_expiry: 0,
      recommendations: 1,
      rotation_overdue: 1,
      static_credentials: 1,
    },
  }),
  nhiExposurePosture: () => ({
    capability: "nhi_exposure_posture",
    coverage: ["credential_inventory", "graph"],
    generated_at: generatedAt,
    findings: [],
    summary: {
      ...emptyRiskSummary,
      findings: 1,
      insecure_transport: 0,
      internet_exposed: 1,
      missing_network_policy: 0,
      public_callbacks: 0,
      recommendations: 1,
      weak_authentication: 0,
      wildcard_reachability: 0,
    },
  }),
  rotationRuns: () => ({
    items: [
      {
        id: "rotation-preview-001",
        tenant_id: tenantID,
        identity_id: "identity-preview-workload",
        trigger: "scheduled",
        status: "succeeded",
        predecessor_fingerprint: "sha256:preview-mesh-old",
        successor_fingerprint: "sha256:preview-mesh-8c12",
        rollback_ref: "preview-evidence://rotation-preview-001/rollback",
        created_at: "2026-07-27T07:40:00Z",
        updated_at: "2026-07-27T07:46:00Z",
        completed_at: "2026-07-27T07:46:00Z",
      },
    ],
  }),
  connectorDeliveries: () => ({ items: [] }),
  auditEvents: () => [],

  discoverySources: () => ({
    items: [
      {
        id: "source-preview-edge",
        tenant_id: tenantID,
        kind: "network",
        name: "Production edge scan",
        config: { cidrs: ["192.0.2.0/28"] },
        created_at: "2026-06-01T09:00:00Z",
        updated_at: generatedAt,
      },
      {
        id: "source-preview-ct",
        tenant_id: tenantID,
        kind: "ct_log",
        name: "Public certificate-transparency logs",
        config: { watched_domains: ["preview-lab.example"] },
        created_at: "2026-06-01T09:05:00Z",
        updated_at: generatedAt,
      },
      {
        id: "source-preview-drift",
        tenant_id: tenantID,
        kind: "drift",
        name: "Production agent drift watch",
        config: { locations: ["datacenter/gateway-04"] },
        created_at: "2026-06-01T09:10:00Z",
        updated_at: generatedAt,
      },
    ],
  }),
  discoveryRuns: () => ({
    items: [
      {
        id: "run-preview-edge",
        tenant_id: tenantID,
        source_id: "source-preview-edge",
        status: "succeeded",
        dry_run: false,
        targets: 14,
        discovered: 3,
        rejected: 0,
        failed: 0,
        created_at: "2026-07-27T07:25:00Z",
        started_at: "2026-07-27T07:25:02Z",
        completed_at: "2026-07-27T07:26:21Z",
      },
      {
        id: "run-preview-ct",
        tenant_id: tenantID,
        source_id: "source-preview-ct",
        status: "succeeded",
        dry_run: false,
        requested_by: "ct-monitor",
        targets: 1,
        discovered: 1,
        rejected: 0,
        failed: 0,
        created_at: "2026-07-27T07:30:00Z",
        started_at: "2026-07-27T07:30:01Z",
        completed_at: "2026-07-27T07:30:08Z",
      },
      {
        id: "run-preview-drift",
        tenant_id: tenantID,
        source_id: "source-preview-drift",
        status: "succeeded",
        dry_run: false,
        requested_by: "agent-preview-gateway-04",
        targets: 1,
        discovered: 1,
        rejected: 0,
        failed: 0,
        created_at: "2026-07-27T07:35:00Z",
        started_at: "2026-07-27T07:35:01Z",
        completed_at: "2026-07-27T07:35:06Z",
      },
    ],
  }),
  discoveryFindings: () => ({
    items: [
      {
        id: "finding-preview-legacy",
        tenant_id: tenantID,
        run_id: "run-preview-edge",
        source_id: "source-preview-edge",
        kind: "x509_certificate",
        ref: "tls://legacy-gateway.preview-lab.example:443",
        fingerprint: "sha256:preview-legacy-2bd7",
        provenance: "network:tls",
        risk_score: 76,
        triage_status: "investigating",
        metadata: { algorithm: "RSA-2048", owner: "unassigned" },
        discovered_at: "2026-07-27T07:26:00Z",
      },
      {
        id: "finding-preview-ct",
        tenant_id: tenantID,
        run_id: "run-preview-ct",
        source_id: "source-preview-ct",
        kind: "x509_certificate",
        ref: "*.payments.preview-lab.example",
        fingerprint: "sha256:preview-ct-91e4",
        provenance: "ct_log:preview-log-2026",
        risk_score: 88,
        triage_status: "unmanaged",
        metadata: { alert: "unexpected SAN outside the approved issuer profile" },
        discovered_at: "2026-07-27T07:30:07Z",
      },
      {
        id: "finding-preview-drift",
        tenant_id: tenantID,
        run_id: "run-preview-drift",
        source_id: "source-preview-drift",
        kind: "credential_drift",
        ref: "gateway-04:/etc/trstctl/tls/current.pem",
        fingerprint: "sha256:preview-legacy-2bd7",
        provenance: "drift:/etc/trstctl/tls/current.pem",
        risk_score: 76,
        triage_status: "investigating",
        metadata: { evidence: "deployed fingerprint differs from the managed revision" },
        discovered_at: "2026-07-27T07:35:05Z",
      },
    ],
  }),
  ctMonitoring: () => ({
    capability: "certificate_transparency_monitoring",
    watched_domains: ["preview-lab.example"],
    logs: [{ url: "https://ct.example.invalid/log", next_index: 4821 }],
    notification_destination: "security-operations",
    outbox_backed_alerts: true,
    sources_path: "/api/v1/discovery/sources",
    runs_path: "/api/v1/discovery/runs",
    findings_path: "/api/v1/discovery/findings",
    watchlist_path: "/api/v1/discovery/ct-monitoring",
    summary: {
      source_count: 1,
      log_count: 1,
      watched_domain_count: 1,
      finding_count: 1,
      open_finding_count: 1,
      unexpected_issuance_count: 0,
      outbox_alert_channel_count: 1,
    },
    findings: [],
  }),
  driftRemediation: () => ({
    capability: "drift_remediation",
    dashboard_path: "/posture",
    sources_path: "/api/v1/discovery/sources",
    runs_path: "/api/v1/discovery/runs",
    findings_path: "/api/v1/discovery/findings",
    summary: {
      source_count: 1,
      finding_count: 1,
      open_finding_count: 1,
      investigating_count: 1,
      remediated_count: 0,
      dismissed_count: 0,
      remediation_decision_count: 1,
      certificate_count: 1,
      secret_count: 0,
      ssh_key_count: 0,
      deleted_count: 0,
      replaced_count: 1,
      relocated_count: 0,
      permission_changed_count: 0,
    },
    findings: [
      {
        finding_id: "finding-preview-drift",
        run_id: "run-preview-drift",
        source_id: "source-preview-drift",
        source_name: "Production agent drift watch",
        credential_class: "x509_certificate",
        drift_type: "replaced",
        ref: "gateway-04:/etc/trstctl/tls/current.pem",
        fingerprint: "sha256:preview-legacy-2bd7",
        provenance: "drift:/etc/trstctl/tls/current.pem",
        risk_score: 76,
        triage_status: "investigating",
        available_decisions: ["investigate", "mark_managed", "dismiss"],
        recommended_action: "Compare the observed certificate with the deployment record.",
        evidence_refs: ["preview-evidence://drift/finding-preview-drift"],
        metadata: { expected_fingerprint: "sha256:preview-legacy-old" },
      },
    ],
  }),
  listCBOMAssets: () => ({
    items: [
      {
        id: "cbom-preview-edge-tls",
        kind: "tls_endpoint",
        location: "edge.preview-lab.example:443",
        algorithm: "RSA",
        key_bits: 2048,
        protocol: "TLS 1.2",
        strength: "legacy",
        out_of_policy: true,
        quantum_vulnerable: true,
        reasons: ["RSA key exchange requires a staged post-quantum migration."],
        migration_generation: "generation-1",
        migration_standard: "NIST FIPS 203/204",
        migration_target: "hybrid ML-KEM + ECDSA",
      },
      {
        id: "cbom-preview-workload",
        kind: "workload_identity",
        location: "kubernetes/payments/api",
        algorithm: "ML-DSA-65",
        strength: "post-quantum",
        out_of_policy: false,
        quantum_vulnerable: false,
        migration_generation: "generation-2",
        migration_standard: "NIST FIPS 204",
        migration_target: "complete",
      },
    ],
    migration_progress: {
      total_assets: 2,
      out_of_policy_assets: 1,
      quantum_vulnerable_assets: 1,
      post_quantum_ready_assets: 1,
      percent_migrated: 50,
    },
  }),
  pqcCampaigns: () => ({
    items: [
      {
        id: "77777777-7777-4777-8777-777777777777",
        tenant_id: tenantID,
        name: "Payments PQC migration",
        owner: "team:payments",
        deadline: "2026-12-01T00:00:00Z",
        wave: "wave-1",
        readiness_criteria: ["Owner approved", "Rollback documented"],
        readiness_status: "pending",
        readiness_evidence_refs: [],
        status: "open",
        finding_count: 1,
        pending_count: 1,
        remediated_count: 0,
        excepted_count: 0,
        automated_execution_available: false,
        automated_execution_note:
          "Campaign tracking and evidence work without a licence. Automated fleet execution is unavailable in this edition; record work performed manually or by another tool.",
        created_at: generatedAt,
        updated_at: generatedAt,
      },
    ],
    next_cursor: "",
  }),

  secretPage: () => ({
    items: [
      { name: "payments/production/database", version: 7, created_at: "2026-05-12T09:00:00Z", updated_at: "2026-07-26T18:40:00Z" },
      { name: "payments/production/webhook", version: 3, created_at: "2026-06-02T11:30:00Z", updated_at: "2026-07-20T10:10:00Z" },
      { name: "platform/ci/signing-token", version: 12, created_at: "2026-02-18T08:00:00Z", updated_at: "2026-07-27T06:00:00Z" },
    ],
  }),

  sshStatus: () => ({
    served: true,
    tenant_id: tenantID,
    authority_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPreviewLabAuthority preview-ca",
    krl_version: 14,
    revoked_count: 3,
    attestors: ["k8s_sat", "aws_iid", "gcp_iit", "azure_imds"],
  }),
  sshFleet: () => ({
    host_count: 2,
    key_count: 19,
    standing_key_count: 5,
    orphaned_key_count: 1,
    hosts_not_under_ca: 1,
    hosts: [
      {
        location: "bastion.preview-lab.example",
        keys: 12,
        standing_keys: 3,
        orphaned_keys: 1,
        under_ca: true,
        key_types: ["ssh-ed25519", "sk-ssh-ed25519"],
        sources: ["agent", "authorized_keys"],
        first_observed: "2026-05-01T00:00:00Z",
        last_observed: generatedAt,
      },
      {
        location: "legacy-admin.preview-lab.example",
        keys: 7,
        standing_keys: 2,
        orphaned_keys: 0,
        under_ca: false,
        key_types: ["ssh-rsa"],
        sources: ["network-scan"],
        first_observed: "2026-06-10T00:00:00Z",
        last_observed: generatedAt,
      },
    ],
  }),

  incidentExecutions: () => ({ items: [incidentExecution] }),
  fleetReissuanceRuns: () => ({ items: [] }),
  remediationPlaybooks: () => ({
    capability: "incident_remediation_playbooks",
    generated_at: generatedAt,
    status: "ready",
    items: [
      {
        id: "nhi-right-size",
        name: "Right-size NHI access",
        summary: translateNow("preview.sample.playbookSummary"),
        action: "right_size",
        capability: "owner_self_remediation",
        status: "available",
        required_inputs: ["target_identity_id", "remove_scopes"],
        evidence_sources: ["risk_projection", "audit_log"],
        external_effect: "outbox_connector_delivery",
      },
    ],
  }),
  remediationPlaybookRuns: () => ({
    items: [
      {
        id: "playbook-run-preview-001",
        tenant_id: tenantID,
        playbook_id: "nhi-right-size",
        action: "right_size",
        target_identity_id: "identity-preview-secret",
        inventory_id: "inventory-preview-secret",
        status: "completed",
        phase: "evidence_recorded",
        scope_delta: { removed: ["database:admin"], retained: ["database:connect"] },
        evidence_refs: ["preview-evidence://playbook/playbook-run-preview-001"],
        rollback_refs: ["preview-evidence://rollback/playbook-run-preview-001"],
        created_at: "2026-07-27T06:40:00Z",
        updated_at: "2026-07-27T06:42:00Z",
      },
    ],
  }),
  ownerRemediationActions: () => ownerQueue,
  remediationOwnerActions: () => ownerQueue,
  connectorCatalog: () => ({
    items: [
      {
        name: "postgresql",
        kind: "database",
        native: true,
        capabilities: ["deploy", "rollback"],
        delivery_mode: "bounded_outbox",
        replay_safety: "reconciled",
        rollback: "restore previous credential",
      },
    ],
  }),

  issuers: () => [
    {
      id: "issuer-preview-root",
      tenant_id: tenantID,
      name: "Preview Lab Root CA",
      kind: "x509_ca",
      internal: true,
      chain: ["Preview Lab Root CA"],
      public_key: "-----BEGIN PUBLIC KEY-----PREVIEWROOT-----END PUBLIC KEY-----",
      created_at: "2025-01-01T00:00:00Z",
    },
    {
      id: "issuer-preview-intermediate",
      tenant_id: tenantID,
      name: "Preview Lab Intermediate CA",
      kind: "x509_ca",
      internal: true,
      chain: ["Preview Lab Root CA", "Preview Lab Intermediate CA"],
      public_key: "-----BEGIN PUBLIC KEY-----PREVIEWINTERMEDIATE-----END PUBLIC KEY-----",
      created_at: "2025-01-02T00:00:00Z",
    },
  ],
  profiles: () => [{ id: "profile-preview-server-tls", name: "server-tls-90d", version: 4, active: true, spec: { ttl: "2160h", key_algorithm: "ECDSA-P256" } }],
  caDiscoveryInventory: () => ({
    summary: { authority_count: 2, external_registry_count: 0, private_count: 2, public_count: 0 },
    items: [
      {
        id: "ca-authority/ca-preview-root",
        source_id: "ca-preview-root",
        source: "ca_hierarchy",
        scope: "private",
        type: "root",
        name: "Preview Lab Root CA",
        status: "active",
        managed: true,
        inventory_path: "/api/v1/ca/authorities",
        issuance_path: "/api/v1/ca/authorities/ca-preview-root/issue",
        discovery_methods: ["ca_hierarchy_projection"],
        serial: "CA01",
        not_after: "2040-01-01T00:00:00Z",
      },
      {
        id: "ca-authority/ca-preview-intermediate",
        source_id: "ca-preview-intermediate",
        source: "ca_hierarchy",
        scope: "private",
        type: "intermediate",
        name: "Preview Lab Intermediate CA",
        status: "active",
        managed: true,
        parent_id: "ca-preview-root",
        inventory_path: "/api/v1/ca/authorities",
        issuance_path: "/api/v1/ca/authorities/ca-preview-intermediate/issue",
        discovery_methods: ["ca_hierarchy_projection"],
        serial: "CA02",
        not_after: "2035-01-01T00:00:00Z",
      },
    ],
  }),
  caAuthorities: () => ({
    items: [
      {
        id: "ca-preview-root",
        tenant_id: tenantID,
        common_name: "Preview Lab Root CA",
        kind: "root",
        status: "active",
        serial: "CA01",
        signer_handle: "preview://offline-root",
        max_path_len: 2,
        created_at: "2025-01-01T00:00:00Z",
        not_after: "2040-01-01T00:00:00Z",
        certificate_pem: "-----BEGIN CERTIFICATE-----PREVIEWROOT-----END CERTIFICATE-----",
        permitted_dns_names: ["preview-lab.example"],
      },
      {
        id: "ca-preview-intermediate",
        tenant_id: tenantID,
        common_name: "Preview Lab Intermediate CA",
        kind: "intermediate",
        status: "active",
        parent_id: "ca-preview-root",
        serial: "CA02",
        signer_handle: "preview://managed/intermediate",
        max_path_len: 1,
        created_at: "2025-01-02T00:00:00Z",
        not_after: "2035-01-01T00:00:00Z",
        certificate_pem: "-----BEGIN CERTIFICATE-----PREVIEWINTERMEDIATE-----END CERTIFICATE-----",
        permitted_dns_names: ["preview-lab.example"],
      },
    ],
  }),
  assessMigration: () => ({
    plan_id: "preview-ca-rollover",
    members: 1,
    migratable: 1,
    guidance: "All members have the required observed facts.",
    unknowns: [],
    waves: [{ id: "canary", ordinal: 1, members: ["identity-preview-api"] }],
  }),
  migrationRuns: () => ({ items: [] }),
};

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function previewRead(method: string): PreviewReadResult {
  const reader = previewReaders[method];
  if (!reader) return { matched: false };
  return { matched: true, value: clone(reader()) };
}
