// SPDX-License-Identifier: MPL-2.0

// Package custody is the vocabulary for stating, per credential, where its
// private key was generated and where it lives (epic B5).
//
// "Whose process created this key" is the first question an auditor asks and
// the one a whitepaper answers worst — because a whitepaper describes the
// intended shape of a system, and an auditor is asking about one certificate.
// docs/custody.md answers it per credential KIND, which is the right level for a
// design review and the wrong level for an audit: it cannot tell you whether the
// certificate in front of you took the modern path or the deprecated one.
//
// So the answer is recorded per credential, from what the issuing code actually
// did rather than from what the documentation says it should. A certificate
// issued from an operator-supplied CSR records that the control plane never held
// the key. One issued through the deprecated server-keygen path records that it
// did. Both are true statements about that certificate, and an auditor can read
// them without trusting either the code or the prose.
//
// The vocabulary is closed and every value means one thing. There is no
// "unknown" that quietly stands in for "we did not record it" — Unrecorded says
// exactly that, and it is a different claim from any of the others.
package custody

import (
	"encoding/json"
	"strings"
)

// KeyOrigin says whose process generated the private key.
type KeyOrigin string

const (
	// OriginRequester: the key was generated by whoever asked for the
	// certificate — an ACME client, an EST client, an agent on its own host, an
	// operator running openssl. A PKCS#10 request travelled up and a certificate
	// travelled down; the control plane signed something it could not read a key
	// from. This is the target shape for every credential kind.
	OriginRequester KeyOrigin = "requester"
	// OriginHostAgent: generated by a trstctl agent on the host the credential
	// serves. A narrower, more useful claim than "requester" when it is true,
	// because it names which machine.
	OriginHostAgent KeyOrigin = "host_agent"
	// OriginDevice: generated on a device that cannot export it — a TPM, a smart
	// card, an HSM-backed store. The strongest custody claim available, and one
	// worth distinguishing from a software key the requester happened to make.
	OriginDevice KeyOrigin = "device"
	// OriginControlPlane: the control plane generated the subject key. It is a
	// deprecated path retained for one release train, and recording it is the
	// point — a credential on this path is one an operator should plan to
	// replace, and they cannot plan for what is not written down.
	OriginControlPlane KeyOrigin = "control_plane"
	// OriginSigner: generated inside the isolated signer process (AN-4). CA keys
	// only — never a subject key.
	OriginSigner KeyOrigin = "signer"
	// OriginUnrecorded: no custody was recorded for this credential. It is NOT a
	// synonym for any of the above and must never be rendered as reassurance:
	// a credential discovered by a scan has an origin, and this says we do not
	// know it rather than guessing.
	OriginUnrecorded KeyOrigin = ""
)

// StorageClass says what holds the private key now.
type StorageClass string

const (
	// StorageLockedMemory: an mlock'd, zeroized buffer, alive for one operation.
	StorageLockedMemory StorageClass = "locked_memory"
	// StorageFile: a file on a host's disk, with the permissions the deployment
	// gave it.
	StorageFile StorageClass = "file"
	// StorageOSStore: a platform certificate store — Windows CNG/CAPI, macOS
	// keychain — whose protection is the platform's rather than ours.
	StorageOSStore StorageClass = "os_store"
	// StoragePKCS11: a token or HSM reached over PKCS#11.
	StoragePKCS11 StorageClass = "pkcs11"
	// StorageDeviceBound: hardware that will not export the key at all.
	StorageDeviceBound StorageClass = "device_bound"
	// StorageUnrecorded: not recorded. Same discipline as OriginUnrecorded.
	StorageUnrecorded StorageClass = ""
)

// Exportability is deliberately a tri-state.
//
// "We did not record whether this key can be exported" and "this key cannot be
// exported" are different sentences, and a boolean would collapse them into the
// reassuring one. An auditor reading a certificate whose exportability is
// unrecorded should see that, not a confident false.
type Exportability string

const (
	// Exportable: the key can be copied off whatever holds it.
	Exportable Exportability = "exportable"
	// NonExportable: the holder will not surrender it.
	NonExportable Exportability = "non_exportable"
	// ExportabilityUnrecorded: not established.
	ExportabilityUnrecorded Exportability = ""
)

// Record is one credential's custody, as observed at issuance.
type Record struct {
	Origin     KeyOrigin     `json:"key_origin,omitempty"`
	Storage    StorageClass  `json:"key_storage,omitempty"`
	Exportable Exportability `json:"key_exportable,omitempty"`
	// GeneratedBy names the specific actor when one is known — an agent common
	// name, a relay, a device identifier. It is what turns "a host agent made
	// it" into an answer an auditor can follow up.
	GeneratedBy string `json:"generated_by,omitempty"`
}

// ControlPlaneHeldKey reports whether the control plane ever held this
// credential's private key. It is the single question docs/custody.md is
// organized around, and the one an auditor asks first.
//
// Unrecorded custody answers false — not because the control plane definitely
// did not hold it, but because this method answers "did we record that it did",
// and the caller is expected to render Unrecorded as unknown rather than as
// either answer. Summary() is what surfaces belong to use for display.
func (r Record) ControlPlaneHeldKey() bool { return r.Origin == OriginControlPlane }

// Recorded reports whether any custody was established at all.
func (r Record) Recorded() bool {
	return r.Origin != OriginUnrecorded || r.Storage != StorageUnrecorded ||
		r.Exportable != ExportabilityUnrecorded
}

// Summary is the operator-facing sentence.
//
// It says what is known and stays silent about what is not, rather than filling
// gaps with defaults. A custody line that reads confidently about facts nobody
// recorded is worse than no line, because an auditor will believe it.
func (r Record) Summary() string {
	if !r.Recorded() {
		return "Key custody was not recorded for this credential."
	}
	var parts []string
	switch r.Origin {
	case OriginRequester:
		parts = append(parts, "The private key was generated by the requester; the control plane never held it")
	case OriginHostAgent:
		who := "a trstctl agent on the host it serves"
		if strings.TrimSpace(r.GeneratedBy) != "" {
			who = "the agent " + r.GeneratedBy + " on the host it serves"
		}
		parts = append(parts, "The private key was generated by "+who+"; the control plane never held it")
	case OriginDevice:
		parts = append(parts, "The private key was generated on the device and cannot leave it")
	case OriginControlPlane:
		parts = append(parts, "The private key was generated BY THE CONTROL PLANE (deprecated path); it was held in locked memory and wiped, but it existed outside the requester")
	case OriginSigner:
		parts = append(parts, "The key was generated inside the isolated signer and never left it")
	}
	switch r.Storage {
	case StorageLockedMemory:
		parts = append(parts, "held in locked, zeroized memory for the operation only")
	case StorageFile:
		parts = append(parts, "stored as a file on the host")
	case StorageOSStore:
		parts = append(parts, "stored in the platform certificate store")
	case StoragePKCS11:
		parts = append(parts, "stored on a PKCS#11 token")
	case StorageDeviceBound:
		parts = append(parts, "bound to hardware that will not export it")
	}
	switch r.Exportable {
	case Exportable:
		parts = append(parts, "and it is exportable")
	case NonExportable:
		parts = append(parts, "and it is non-exportable")
	}
	return strings.Join(parts, ", ") + "."
}

// ValidOrigin reports whether v is a value this system records.
func ValidOrigin(v KeyOrigin) bool {
	switch v {
	case OriginRequester, OriginHostAgent, OriginDevice, OriginControlPlane, OriginSigner, OriginUnrecorded:
		return true
	default:
		return false
	}
}

// ValidStorage reports whether v is a value this system records.
func ValidStorage(v StorageClass) bool {
	switch v {
	case StorageLockedMemory, StorageFile, StorageOSStore, StoragePKCS11, StorageDeviceBound, StorageUnrecorded:
		return true
	default:
		return false
	}
}

// ValidExportability reports whether v is a value this system records.
func ValidExportability(v Exportability) bool {
	switch v {
	case Exportable, NonExportable, ExportabilityUnrecorded:
		return true
	default:
		return false
	}
}

// Which process generates a deployment target's subject key (epic B2).
//
// This lives here rather than in internal/server or internal/api because BOTH
// need it and neither may import the other: the control plane decides the path,
// the console reports it, and the two must agree exactly. A copy in each package
// was the first shape of this and it was wrong — not because duplication is
// untidy, but because a console that read the marker differently would report a
// target as migrated while the control plane kept sending it keys, which is
// precisely the false claim this epic exists to make impossible.
//
// One definition, imported twice, cannot drift.

// ExecutorConfigKey is the deployment-target config key naming the executor.
const ExecutorConfigKey = "executor"

// ExecutorAgent is the value that opts a target into host-generated keys.
const ExecutorAgent = "agent"

// TargetExecutorIsAgent reports whether a target's config opts it into
// host-generated keys.
//
// Absent means no, and so does unparseable. A target whose config predates this
// feature must not change behaviour because a new version shipped, and the
// failure direction is the one that matters: reading "agent" from a config that
// does not say it would both refuse that target's deploys and report it as
// migrated when it is not.
//
// The value must be a STRING. A config with `executor: true` is an error, and
// coercing it to consent would migrate a target its operator never marked.
func TargetExecutorIsAgent(cfg []byte) bool {
	if len(cfg) == 0 {
		return false
	}
	var fields map[string]any
	if err := json.Unmarshal(cfg, &fields); err != nil {
		return false
	}
	v, ok := fields[ExecutorConfigKey].(string)
	if !ok {
		return false
	}
	return strings.EqualFold(strings.TrimSpace(v), ExecutorAgent)
}
