{{- if eq .Values.signer.mode "isolated" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trustctl.fullname" . }}-signer
  labels:
    {{- include "trustctl.labels" . | nindent 4 }}
    app.kubernetes.io/component: signer
spec:
  type: ClusterIP
  selector:
    {{- include "trustctl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: signer
  ports:
    - name: grpc-mtls
      port: 9443
      targetPort: grpc-mtls
{{- end }}
