package server

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"testing"

	"github.com/jackc/pgx/v5"

	"trstctl.com/trstctl/internal/config"
	"trstctl.com/trstctl/internal/crypto"
	"trstctl.com/trstctl/internal/crypto/mtls"
)

func TestServedEnrollmentTokenPersistsAllowedIdentityRED003(t *testing.T) {
	h := newServedHarness(t, config.Protocols{}, withAgentChannel)
	token := seedScopedToken(t, h.store, h.tenant, "agents:write")

	status, body := secretsReqKey(t, h, http.MethodPost, "/api/v1/agents/enrollment-tokens", token,
		"red-003-agent-token-pin", map[string]any{"allowed_identity": "node-a"})
	if status != http.StatusCreated {
		t.Fatalf("create enrollment token = %d body %s, want 201", status, body)
	}

	var stored string
	err := h.store.WithTenant(context.Background(), h.tenant, func(tx pgx.Tx) error {
		return tx.QueryRow(context.Background(),
			`SELECT allowed_identity FROM agent_bootstrap_tokens WHERE tenant_id = $1`,
			h.tenant).Scan(&stored)
	})
	if err != nil {
		t.Fatalf("read stored allowed identity: %v", err)
	}
	if stored != "node-a" {
		t.Fatalf("stored allowed_identity = %q, want node-a", stored)
	}
}

func TestServedBootstrapRejectsCSRIdentityMismatchRED003(t *testing.T) {
	h := newServedHarness(t, config.Protocols{}, withAgentChannel)
	token, err := h.srv.agentEnroll.IssueBootstrapToken(context.Background(), h.tenant, "node-a")
	if err != nil {
		t.Fatalf("issue pinned bootstrap token: %v", err)
	}
	csr := agentCSRWithDNS(t, "node-a", []string{"rogue-node"})

	body, _ := json.Marshal(map[string]string{
		"token": token,
		"csr":   base64.StdEncoding.EncodeToString(csr),
	})
	req, err := http.NewRequest(http.MethodPost, h.ts.URL+"/enroll/bootstrap", bytes.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := h.ts.Client().Do(req)
	if err != nil {
		t.Fatalf("POST /enroll/bootstrap: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("bootstrap with mismatched CSR SAN = %d, want 401", resp.StatusCode)
	}
}

func agentCSRWithDNS(t *testing.T, cn string, dns []string) []byte {
	t.Helper()
	key, err := crypto.GenerateLockedKey(crypto.ECDSAP256)
	if err != nil {
		t.Fatalf("generate CSR key: %v", err)
	}
	t.Cleanup(key.Destroy)
	csr, err := crypto.CreateCertificateRequest(crypto.CertificateRequestTemplate{
		CommonName: cn,
		DNSNames:   dns,
	}, key)
	if err != nil {
		t.Fatalf("CreateCertificateRequest: %v", err)
	}
	if !mtls.IsCSR(csr) {
		t.Fatal("generated bytes are not a CSR")
	}
	return csr
}
