// SPDX-License-Identifier: BUSL-1.1

// Workload-agent predecessor co-sign contract (PCAS-claim-19, INT-16). The platform
// signer/orchestrator forms a succession commitment and asks the workload agent —
// which holds the predecessor key — to co-sign it. The request carries the STRUCTURED
// commitment fields (a canonical, reversible encoding), NEVER an opaque digest, so the
// agent reconstructs and domain-separates the commitment itself and can never be used
// as a generic signing oracle (FIG. 5 oracle-prevention). Only the predecessor
// signature — public material — crosses back.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/succession/agent/cosignpb/cosign.proto

package cosignpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoSignerService_CoSign_FullMethodName = "/trstctl.pcas.agent.v1.CoSignerService/CoSign"
)

// CoSignerServiceClient is the client API for CoSignerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoSignerService is served by the workload agent. It is deliberately minimal: a
// single co-sign method under a distinct key-usage purpose.
type CoSignerServiceClient interface {
	// CoSign returns the predecessor co-signature over the commitment the agent
	// reconstructs from the structured fields. The agent refuses any request outside
	// its co-sign purpose, or whose identity/tenant/deployment/predecessor-key is not
	// its own.
	CoSign(ctx context.Context, in *CoSignRequest, opts ...grpc.CallOption) (*CoSignResponse, error)
}

type coSignerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoSignerServiceClient(cc grpc.ClientConnInterface) CoSignerServiceClient {
	return &coSignerServiceClient{cc}
}

func (c *coSignerServiceClient) CoSign(ctx context.Context, in *CoSignRequest, opts ...grpc.CallOption) (*CoSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoSignResponse)
	err := c.cc.Invoke(ctx, CoSignerService_CoSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoSignerServiceServer is the server API for CoSignerService service.
// All implementations must embed UnimplementedCoSignerServiceServer
// for forward compatibility.
//
// CoSignerService is served by the workload agent. It is deliberately minimal: a
// single co-sign method under a distinct key-usage purpose.
type CoSignerServiceServer interface {
	// CoSign returns the predecessor co-signature over the commitment the agent
	// reconstructs from the structured fields. The agent refuses any request outside
	// its co-sign purpose, or whose identity/tenant/deployment/predecessor-key is not
	// its own.
	CoSign(context.Context, *CoSignRequest) (*CoSignResponse, error)
	mustEmbedUnimplementedCoSignerServiceServer()
}

// UnimplementedCoSignerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoSignerServiceServer struct{}

func (UnimplementedCoSignerServiceServer) CoSign(context.Context, *CoSignRequest) (*CoSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoSign not implemented")
}
func (UnimplementedCoSignerServiceServer) mustEmbedUnimplementedCoSignerServiceServer() {}
func (UnimplementedCoSignerServiceServer) testEmbeddedByValue()                         {}

// UnsafeCoSignerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoSignerServiceServer will
// result in compilation errors.
type UnsafeCoSignerServiceServer interface {
	mustEmbedUnimplementedCoSignerServiceServer()
}

func RegisterCoSignerServiceServer(s grpc.ServiceRegistrar, srv CoSignerServiceServer) {
	// If the following call panics, it indicates UnimplementedCoSignerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoSignerService_ServiceDesc, srv)
}

func _CoSignerService_CoSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoSignerServiceServer).CoSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoSignerService_CoSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoSignerServiceServer).CoSign(ctx, req.(*CoSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoSignerService_ServiceDesc is the grpc.ServiceDesc for CoSignerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoSignerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trstctl.pcas.agent.v1.CoSignerService",
	HandlerType: (*CoSignerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoSign",
			Handler:    _CoSignerService_CoSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/succession/agent/cosignpb/cosign.proto",
}
