// SPDX-License-Identifier: BUSL-1.1

// Package tpm is the TPM 2.0 key-management backend (S9.6), built from the S9.1 backend
// template behind the AN-3 crypto boundary. GenerateKey asks the TPM to create a key and
// returns a crypto.Signer that signs via the TPM — the private key never leaves the device.
// Digests route through internal/crypto (no crypto/*); the backend itself never touches
// private key material.
//
// Linux production uses the google/go-tpm binding against /dev/tpmrm0, /dev/tpm0,
// or a swtpm Unix socket; other platforms fail closed. The Device seam keeps fast
// unit tests small, while the launched-binary DoD proof drives the real TPM command
// protocol through swtpm and independent tpm2-tools readback.
package tpm

import (
	"context"
	"errors"
	"fmt"

	"trstctl.com/trstctl/internal/crypto"
)

// Device is the injectable TPM 2.0 seam. Linux production drives it with go-tpm;
// fast tests inject a software-backed double. Created keys are
// referenced by an opaque handle string (a transient TPM handle or a persisted context);
// the private key never crosses this boundary — only the public key (DER SubjectPublicKeyInfo)
// and signatures over caller-supplied digests do.
type Device interface {
	// CreateKey provisions a signing key in the TPM for alg and returns an opaque handle
	// plus the public key as DER SubjectPublicKeyInfo (PKIX).
	CreateKey(alg crypto.Algorithm) (handle string, publicDER []byte, err error)
	// Sign signs digest with the key named by handle and returns the raw signature.
	Sign(handle string, digest []byte, opts crypto.SignOptions) (sig []byte, err error)
	// Close releases the device (closes the TPM connection/socket).
	Close() error
}

// LifecycleDevice is implemented by a production TPM binding that can retire a
// persistent key handle. Many TPMs cannot express a reversible "disabled" bit
// for an unrestricted signing object, so RevokeKey removes the persistent
// object immediately; ZeroizeKey is then an idempotent confirmation that the
// object is absent. The support matrix documents this stronger-than-requested
// revoke behavior.
type LifecycleDevice interface {
	RevokeKey(handle string) error
	ZeroizeKey(handle string) error
}

// OperationDevice maps a durable operation ID to one deterministic persistent
// handle and reads that handle back before provisioning. Terminal operations
// confirm the persistent object is absent, making a lost response replay-safe.
type OperationDevice interface {
	CreateKeyForOperation(operationID string, alg crypto.Algorithm) (handle string, publicDER []byte, err error)
	RevokeKeyForOperation(operationID, handle string) error
	ZeroizeKeyForOperation(operationID, handle string) error
}

// Backend is a TPM 2.0 crypto.Backend. It owns a Device and turns the generic backend
// contract into TPM operations; it never holds private key material itself.
type Backend struct {
	dev Device
}

var (
	_ crypto.Backend                          = (*Backend)(nil)
	_ crypto.RemoteKeyLifecycle               = (*Backend)(nil)
	_ crypto.OperationAwareRemoteKeyLifecycle = (*Backend)(nil)
	_ crypto.RemoteKeyDigestSigner            = (*Backend)(nil)
)

// Option configures a Backend.
type Option func(*Backend)

// New returns a TPM 2.0 backend that drives dev. Production passes the go-tpm-backed
// Linux device; fast tests pass a software-backed double.
func New(dev Device, opts ...Option) *Backend {
	b := &Backend{dev: dev}
	for _, o := range opts {
		o(b)
	}
	return b
}

// Name identifies the backend.
func (b *Backend) Name() string { return "tpm2" }

// GenerateKey provisions a signing key in the TPM and returns a Signer for it. TPM 2.0
// devices commonly support ECDSA P-256 and RSA-2048; the device decides which algorithms
// it accepts, so unsupported algorithms surface as a CreateKey error.
func (b *Backend) GenerateKey(alg crypto.Algorithm) (crypto.Signer, error) {
	if b.dev == nil {
		return nil, errors.New("tpm: no device configured")
	}
	handle, pubDER, err := b.dev.CreateKey(alg)
	if err != nil {
		return nil, fmt.Errorf("tpm: create key: %w", err)
	}
	if len(pubDER) == 0 {
		return nil, fmt.Errorf("tpm: device returned an empty public key for %s", alg)
	}
	return &tpmSigner{
		dev:    b.dev,
		handle: handle,
		alg:    alg,
		pub:    crypto.PublicKey{Algorithm: alg, DER: pubDER},
	}, nil
}

// Close releases the underlying device.
func (b *Backend) Close() error {
	if b.dev == nil {
		return nil
	}
	return b.dev.Close()
}

// GenerateManagedKey provisions a persistent TPM signing object and returns its
// opaque TPM handle. The private key is generated by and remains in the TPM.
func (b *Backend) GenerateManagedKey(ctx context.Context, alg crypto.Algorithm) (crypto.Signer, crypto.KeyRef, error) {
	if err := ctx.Err(); err != nil {
		return nil, crypto.KeyRef{}, err
	}
	signer, err := b.GenerateKey(alg)
	if err != nil {
		return nil, crypto.KeyRef{}, err
	}
	ts, ok := signer.(*tpmSigner)
	if !ok {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: unexpected signer type %T", signer)
	}
	return signer, crypto.KeyRef{ID: ts.handle, Algorithm: alg}, nil
}

func (b *Backend) GenerateManagedKeyForOperation(ctx context.Context, operationID string, alg crypto.Algorithm) (crypto.Signer, crypto.KeyRef, error) {
	if err := validateOperation(ctx, operationID); err != nil {
		return nil, crypto.KeyRef{}, err
	}
	device, ok := b.dev.(OperationDevice)
	if !ok {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: device does not support durable operation reconciliation")
	}
	handle, publicDER, err := device.CreateKeyForOperation(operationID, alg)
	if err != nil {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: reconcile persistent key: %w", err)
	}
	if handle == "" || len(publicDER) == 0 {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: device returned an incomplete managed key")
	}
	signer := &tpmSigner{dev: b.dev, handle: handle, alg: alg, pub: crypto.PublicKey{Algorithm: alg, DER: publicDER}}
	return signer, crypto.KeyRef{ID: handle, Algorithm: alg}, nil
}

func (b *Backend) RotateKey(ctx context.Context, ref crypto.KeyRef) (crypto.Signer, crypto.KeyRef, error) {
	if ref.ID == "" {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: rotate requires a key ref")
	}
	return b.GenerateManagedKey(ctx, ref.Algorithm)
}

func (b *Backend) RotateKeyForOperation(ctx context.Context, operationID string, ref crypto.KeyRef) (crypto.Signer, crypto.KeyRef, error) {
	if ref.ID == "" {
		return nil, crypto.KeyRef{}, fmt.Errorf("tpm: rotate requires a key ref")
	}
	return b.GenerateManagedKeyForOperation(ctx, operationID, ref.Algorithm)
}

func (b *Backend) RevokeKey(ctx context.Context, ref crypto.KeyRef) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if ref.ID == "" {
		return fmt.Errorf("tpm: revoke requires a key ref")
	}
	lifecycle, ok := b.dev.(LifecycleDevice)
	if !ok {
		return fmt.Errorf("tpm: device does not support persistent-key lifecycle")
	}
	return lifecycle.RevokeKey(ref.ID)
}

func (b *Backend) RevokeKeyForOperation(ctx context.Context, operationID string, ref crypto.KeyRef) error {
	if err := validateOperation(ctx, operationID); err != nil {
		return err
	}
	if ref.ID == "" {
		return fmt.Errorf("tpm: revoke requires a key ref")
	}
	device, ok := b.dev.(OperationDevice)
	if !ok {
		return fmt.Errorf("tpm: device does not support durable operation reconciliation")
	}
	return device.RevokeKeyForOperation(operationID, ref.ID)
}

func (b *Backend) ZeroizeKey(ctx context.Context, ref crypto.KeyRef) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if ref.ID == "" {
		return fmt.Errorf("tpm: zeroize requires a key ref")
	}
	lifecycle, ok := b.dev.(LifecycleDevice)
	if !ok {
		return fmt.Errorf("tpm: device does not support persistent-key lifecycle")
	}
	return lifecycle.ZeroizeKey(ref.ID)
}

func (b *Backend) ZeroizeKeyForOperation(ctx context.Context, operationID string, ref crypto.KeyRef) error {
	if err := validateOperation(ctx, operationID); err != nil {
		return err
	}
	if ref.ID == "" {
		return fmt.Errorf("tpm: zeroize requires a key ref")
	}
	device, ok := b.dev.(OperationDevice)
	if !ok {
		return fmt.Errorf("tpm: device does not support durable operation reconciliation")
	}
	return device.ZeroizeKeyForOperation(operationID, ref.ID)
}

func validateOperation(ctx context.Context, operationID string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if operationID == "" || len(operationID) > 256 {
		return fmt.Errorf("tpm: durable operation id is required and must be at most 256 bytes")
	}
	return nil
}

func (b *Backend) SignManagedDigest(ctx context.Context, ref crypto.KeyRef, digest []byte, opts crypto.SignOptions) ([]byte, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if ref.ID == "" {
		return nil, fmt.Errorf("tpm: sign requires a key ref")
	}
	return b.dev.Sign(ref.ID, digest, opts)
}

// tpmSigner signs a digest via the TPM; the key never leaves the device.
type tpmSigner struct {
	dev    Device
	handle string
	alg    crypto.Algorithm
	pub    crypto.PublicKey
}

func (s *tpmSigner) Public() crypto.PublicKey    { return s.pub }
func (s *tpmSigner) Algorithm() crypto.Algorithm { return s.alg }

// Sign hashes message through the crypto boundary (AN-3) and asks the TPM to sign the
// resulting digest. Routing the digest in (rather than the message) matches how TPM 2.0
// signing works and keeps hashing inside internal/crypto.
func (s *tpmSigner) Sign(message []byte, opts crypto.SignOptions) ([]byte, error) {
	digest, err := crypto.Digest(hashOf(opts), message)
	if err != nil {
		return nil, err
	}
	sig, err := s.dev.Sign(s.handle, digest, opts)
	if err != nil {
		return nil, fmt.Errorf("tpm: sign: %w", err)
	}
	return sig, nil
}

// hashOf defaults an unset hash to SHA-256, matching SignOptions' documented default.
func hashOf(opts crypto.SignOptions) crypto.Hash {
	if opts.Hash == "" {
		return crypto.SHA256
	}
	return opts.Hash
}
