// SPDX-License-Identifier: BUSL-1.1

package api

import (
	"context"
	"errors"
	"net/http"
	"strings"

	"trstctl.com/trstctl/internal/store"
)

// ErrACMEDNS01QualificationUnavailable means the running control plane has no
// production DNS-01 automation boundary to test. The console must say that
// plainly instead of pretending that validating form fields tested a provider.
var ErrACMEDNS01QualificationUnavailable = errors.New("ACME DNS-01 provider qualification is not configured")

// ErrACMEDNS01QualificationRunNotFound is deliberately separate from provider
// config lookup so a recovery request cannot reveal another tenant's run.
var ErrACMEDNS01QualificationRunNotFound = errors.New("ACME DNS-01 qualification run not found")

// ACMEDNS01QualificationRequest names the public DNS identity whose configured
// provider path should be reviewed or exercised. Probe material is generated by
// the server and never accepted from or returned to a browser.
type ACMEDNS01QualificationRequest struct {
	Domain string `json:"domain"`
}

// ACMEDNS01QualificationCheck is one server-owned readiness assertion and the
// exact safe recovery when it is blocked.
type ACMEDNS01QualificationCheck struct {
	ID       string `json:"id"`
	Label    string `json:"label"`
	Passed   bool   `json:"passed"`
	Detail   string `json:"detail"`
	Recovery string `json:"recovery"`
}

// ACMEDNS01QualificationPreview is an effect-free review of one exact provider
// config and domain. Reference FIELD NAMES are public metadata; reference values,
// provider configuration values, and the future TXT probe are not.
type ACMEDNS01QualificationPreview struct {
	Ready                     bool                          `json:"ready"`
	EffectFree                bool                          `json:"effect_free"`
	ConfigID                  string                        `json:"config_id"`
	ConfigName                string                        `json:"config_name"`
	Provider                  string                        `json:"provider"`
	Domain                    string                        `json:"domain"`
	RecordName                string                        `json:"record_name"`
	Wildcard                  bool                          `json:"wildcard"`
	CredentialReferenceFields []string                      `json:"credential_reference_fields"`
	Checks                    []ACMEDNS01QualificationCheck `json:"checks"`
	Blockers                  []string                      `json:"blockers"`
	PreviewWrites             []string                      `json:"preview_writes"`
	PreviewExternalEffects    []string                      `json:"preview_external_effects"`
	PreviewSignerCalls        []string                      `json:"preview_signer_calls"`
	ExecuteWrites             []string                      `json:"execute_writes"`
	ExecuteExternalEffects    []string                      `json:"execute_external_effects"`
	ExecuteSignerCalls        []string                      `json:"execute_signer_calls"`
	RecoverySteps             []string                      `json:"recovery_steps"`
	LeastPrivilegeChecklist   []string                      `json:"least_privilege_checklist"`
	SecretDataHandling        string                        `json:"secret_data_handling"`
}

// ACMEDNS01QualificationRun is sanitized durable evidence for one real probe.
// Outbox row identifiers are intentionally omitted: they would not help an ELI5
// operator and would couple the browser to recovery authority held by the server.
type ACMEDNS01QualificationRun struct {
	ID                 string   `json:"id"`
	ConfigID           string   `json:"config_id"`
	ConfigName         string   `json:"config_name"`
	Provider           string   `json:"provider"`
	Domain             string   `json:"domain"`
	RecordName         string   `json:"record_name"`
	Status             string   `json:"status"`
	Stage              string   `json:"stage"`
	PropagationStatus  string   `json:"propagation_status"`
	CleanupStatus      string   `json:"cleanup_status"`
	ErrorCategory      string   `json:"error_category,omitempty"`
	Attempts           int      `json:"attempts"`
	StartedAt          string   `json:"started_at"`
	CompletedAt        string   `json:"completed_at,omitempty"`
	DurationMS         int64    `json:"duration_ms"`
	RecoverySteps      []string `json:"recovery_steps"`
	SecretDataHandling string   `json:"secret_data_handling"`
}

type ACMEDNS01QualificationRunList struct {
	Items []ACMEDNS01QualificationRun `json:"items"`
}

// ACMEDNS01QualificationService is implemented by the assembled server so the
// API cannot invent provider readiness from browser-supplied observations.
type ACMEDNS01QualificationService interface {
	PreviewACMEDNS01Qualification(context.Context, string, string, ACMEDNS01QualificationRequest) (ACMEDNS01QualificationPreview, error)
	RunACMEDNS01Qualification(context.Context, string, string, string, ACMEDNS01QualificationRequest) (ACMEDNS01QualificationRun, error)
	ListACMEDNS01QualificationRuns(context.Context, string, string, int) ([]ACMEDNS01QualificationRun, error)
	RetryACMEDNS01QualificationCleanup(context.Context, string, string, string) (ACMEDNS01QualificationRun, error)
}

// WithACMEDNS01Qualification attaches the late-bound, production DNS-01
// automation. The Server pointer is safe to attach before protocol construction;
// each method reads the assembled runtime at request time.
func WithACMEDNS01Qualification(service ACMEDNS01QualificationService) Option {
	return func(c *config) { c.acmeDNS01Qualification = service }
}

func (a *API) previewACMEDNS01Qualification(w http.ResponseWriter, r *http.Request) {
	tenantID, ok := a.tenant(r)
	if !ok {
		a.writeProblem(w, problemUnauthorized())
		return
	}
	if a.acmeDNS01Qualification == nil {
		a.writeError(w, errStatus(http.StatusServiceUnavailable, ErrACMEDNS01QualificationUnavailable.Error()))
		return
	}
	var req ACMEDNS01QualificationRequest
	if err := decodeJSON(r, &req); err != nil {
		a.writeError(w, errWithStatus(http.StatusBadRequest, err))
		return
	}
	req.Domain = strings.TrimSpace(req.Domain)
	if req.Domain == "" {
		a.writeError(w, errStatus(http.StatusBadRequest, "domain is required"))
		return
	}
	out, err := a.acmeDNS01Qualification.PreviewACMEDNS01Qualification(r.Context(), tenantID, r.PathValue("id"), req)
	if err != nil {
		a.writeACMEDNS01QualificationError(w, err)
		return
	}
	a.writeJSON(w, http.StatusOK, out)
}

//trstctl:mutation
func (a *API) runACMEDNS01Qualification(w http.ResponseWriter, r *http.Request) {
	idempotencyKey := r.Header.Get("Idempotency-Key")
	configID := r.PathValue("id")
	a.mutateDurable(w, r, idempotencyKey, func(ctx context.Context, tenantID string) (int, any, error) {
		if a.acmeDNS01Qualification == nil {
			return 0, nil, ErrACMEDNS01QualificationUnavailable
		}
		var req ACMEDNS01QualificationRequest
		if err := decodeJSON(r, &req); err != nil {
			return 0, nil, errWithStatus(http.StatusBadRequest, err)
		}
		req.Domain = strings.TrimSpace(req.Domain)
		if req.Domain == "" {
			return 0, nil, errStatus(http.StatusBadRequest, "domain is required")
		}
		out, err := a.acmeDNS01Qualification.RunACMEDNS01Qualification(ctx, tenantID, configID, idempotencyKey, req)
		return http.StatusCreated, out, err
	})
}

func (a *API) listACMEDNS01QualificationRuns(w http.ResponseWriter, r *http.Request) {
	tenantID, ok := a.tenant(r)
	if !ok {
		a.writeProblem(w, problemUnauthorized())
		return
	}
	if a.acmeDNS01Qualification == nil {
		a.writeError(w, errStatus(http.StatusServiceUnavailable, ErrACMEDNS01QualificationUnavailable.Error()))
		return
	}
	items, err := a.acmeDNS01Qualification.ListACMEDNS01QualificationRuns(r.Context(), tenantID, r.PathValue("id"), 25)
	if err != nil {
		a.writeACMEDNS01QualificationError(w, err)
		return
	}
	a.writeJSON(w, http.StatusOK, ACMEDNS01QualificationRunList{Items: items})
}

//trstctl:mutation
func (a *API) retryACMEDNS01QualificationCleanup(w http.ResponseWriter, r *http.Request) {
	idempotencyKey := r.Header.Get("Idempotency-Key")
	runID := r.PathValue("run_id")
	a.mutateDurable(w, r, idempotencyKey, func(ctx context.Context, tenantID string) (int, any, error) {
		if a.acmeDNS01Qualification == nil {
			return 0, nil, ErrACMEDNS01QualificationUnavailable
		}
		out, err := a.acmeDNS01Qualification.RetryACMEDNS01QualificationCleanup(ctx, tenantID, runID, idempotencyKey)
		return http.StatusOK, out, err
	})
}

func (a *API) writeACMEDNS01QualificationError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, store.ErrACMEDNS01ProviderConfigNotFound):
		a.writeError(w, errStatus(http.StatusNotFound, "ACME DNS-01 provider config not found"))
	case errors.Is(err, ErrACMEDNS01QualificationUnavailable):
		a.writeError(w, errStatus(http.StatusServiceUnavailable, ErrACMEDNS01QualificationUnavailable.Error()))
	case errors.Is(err, ErrACMEDNS01QualificationRunNotFound):
		a.writeError(w, errStatus(http.StatusNotFound, ErrACMEDNS01QualificationRunNotFound.Error()))
	default:
		a.writeError(w, err)
	}
}
