package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type operation struct {
	OperationID string `json:"operationId"`
}

type route struct {
	Name string
	OpID string
}

var wanted = []route{
	{Name: "CreateProfile", OpID: "createProfile"},
	{Name: "GetProfileVersion", OpID: "getProfileVersion"},
	{Name: "IssuePKISecret", OpID: "issuePKISecret"},
	{Name: "CreateSecret", OpID: "createSecret"},
	{Name: "GetSecret", OpID: "getSecret"},
	{Name: "RotateSecret", OpID: "rotateSecret"},
	{Name: "DeleteSecret", OpID: "deleteSecret"},
}

func main() {
	raw, err := os.ReadFile("clients/sdk/openapi.json")
	if err != nil {
		fatal(err)
	}
	var doc struct {
		Paths map[string]map[string]operation `json:"paths"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		fatal(err)
	}

	type foundRoute struct {
		Method string
		Path   string
	}
	found := map[string]foundRoute{}
	for path, methods := range doc.Paths {
		for method, op := range methods {
			if op.OperationID == "" {
				continue
			}
			found[op.OperationID] = foundRoute{Method: strings.ToUpper(method), Path: path}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by go run ./scripts/gen-terraform-provider-routes; DO NOT EDIT.\n")
	b.WriteString("package terraformprovider\n\n")
	b.WriteString("const (\n")
	for _, want := range wanted {
		got, ok := found[want.OpID]
		if !ok {
			fatal(fmt.Errorf("OpenAPI operation %q not found", want.OpID))
		}
		fmt.Fprintf(&b, "\troute%sMethod = %q\n", want.Name, got.Method)
		fmt.Fprintf(&b, "\troute%sPath   = %q\n", want.Name, got.Path)
	}
	b.WriteString(")\n")

	// Keep the generated file deterministic even when the input map order changes.
	keys := make([]string, 0, len(wanted))
	for _, want := range wanted {
		keys = append(keys, want.OpID)
	}
	sort.Strings(keys)
	b.WriteString("\nvar terraformProviderOperationIDs = []string{\n")
	for _, opID := range keys {
		fmt.Fprintf(&b, "\t%q,\n", opID)
	}
	b.WriteString("}\n")

	if err := os.WriteFile("internal/terraformprovider/openapi_routes.gen.go", []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "gen-terraform-provider-routes: %v\n", err)
	os.Exit(1)
}
