#!/usr/bin/env python3
"""Generate Python TypedDict aliases from the pinned trstctl OpenAPI contract."""

from __future__ import annotations

import json
import keyword
import re
import sys
from pathlib import Path
from typing import Any


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_types.py <openapi.json> <output.py>", file=sys.stderr)
        return 2
    spec_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    spec = json.loads(spec_path.read_text())
    schemas = spec.get("components", {}).get("schemas", {})
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(schemas))
    return 0


def render(schemas: dict[str, Any]) -> str:
    lines = [
        "# Code generated by clients/sdk/python/scripts/gen_types.py; DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from typing import Any, TypedDict",
        "",
    ]
    for name in sorted(schemas):
        py_name = type_name(name)
        schema = schemas[name]
        if schema.get("type") == "object" or "properties" in schema:
            lines.append(f"{py_name} = TypedDict(")
            lines.append(f"    {py_name!r},")
            lines.append("    {")
            for prop, prop_schema in sorted(schema.get("properties", {}).items()):
                lines.append(f"        {prop!r}: {type_expr(prop_schema)},")
            lines.append("    },")
            lines.append("    total=False,")
            lines.append(")")
        else:
            lines.append(f"{py_name} = {type_expr(schema)}")
        lines.append("")
    lines.append("Schema = dict[str, Any]")
    lines.append("")
    return "\n".join(lines)


def type_name(raw: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z_]", "_", raw)
    if not cleaned or cleaned[0].isdigit() or keyword.iskeyword(cleaned):
        cleaned = "_" + cleaned
    return cleaned


def type_expr(schema: dict[str, Any]) -> str:
    if not isinstance(schema, dict):
        return "Any"
    if "$ref" in schema:
        return "dict[str, Any]"
    typ = schema.get("type")
    if isinstance(typ, list):
        typ = next((t for t in typ if t != "null"), typ[0] if typ else None)
    if typ == "string":
        return "str"
    if typ == "integer":
        return "int"
    if typ == "number":
        return "float"
    if typ == "boolean":
        return "bool"
    if typ == "array":
        return f"list[{type_expr(schema.get('items', {}))}]"
    if typ == "object":
        return "dict[str, Any]"
    return "Any"


if __name__ == "__main__":
    raise SystemExit(main())
