// SPDX-License-Identifier: MPL-2.0

package config

import (
	"fmt"
	"net/netip"
	"net/url"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
)

// NativeConnectorNames is the closed set compiled into the shipped control
// plane. Operators explicitly enable members; an empty list exposes no native
// target because deployment credentials must never be sent merely because code
// exists in the binary.
var NativeConnectorNames = []string{
	"nginx", "apache", "caddy", "envoy", "iis", "haproxy", "f5",
	"netscaler", "a10", "kemp", "cisco", "fortigate", "paloalto",
	"postfix", "traefik", "aws-acm", "azure-keyvault",
	"gcp-certificate-manager", "java-keystore", "postgresql", "mysql",
	"rabbitmq", "elasticsearch", "tomcat",
}

// Connectors is operator-owned policy for native deployment integrations.
// Tenant target rows hold only target metadata and secret:// references. They
// cannot grant themselves filesystem roots, process commands, private network
// ranges, or plaintext HTTP.
type Connectors struct {
	Enabled           []string                         `json:"enabled,omitempty"`
	HTTPTimeout       string                           `json:"http_timeout,omitempty"`
	AllowPrivateCIDRs []string                         `json:"allow_private_cidrs,omitempty"`
	AllowInsecureHTTP bool                             `json:"allow_insecure_http,omitempty"`
	LocalProfiles     map[string]LocalConnectorProfile `json:"local_profiles,omitempty"`
	RightSize         []ConnectorRightSizeBinding      `json:"right_size,omitempty"`
}

// ConnectorRightSizeBinding maps one tenant's remediation connector name to an
// operator-controlled entitlement API. The token is a tenant secret-store
// reference resolved only for one outbox attempt; it is never stored here.
type ConnectorRightSizeBinding struct {
	TenantID  string `json:"tenant_id"`
	Connector string `json:"connector"`
	Endpoint  string `json:"endpoint"`
	TokenRef  string `json:"token_ref"`
}

var connectorRightSizeName = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*$`)

// LocalConnectorProfile constrains a co-resident/shared-volume target. Command
// and Args are one exact activation executable; no shell expansion occurs.
type LocalConnectorProfile struct {
	AllowedRoots []string               `json:"allowed_roots,omitempty"`
	Actions      []LocalConnectorAction `json:"actions,omitempty"`
}

// LocalConnectorAction maps one connector-owned logical executable name to an
// exact operator executable. PassArgs forwards only argv generated by the
// compiled connector implementation, never arbitrary tenant argv.
type LocalConnectorAction struct {
	LogicalName string   `json:"logical_name"`
	LogicalArgs []string `json:"logical_args,omitempty"`
	Command     string   `json:"command"`
	Args        []string `json:"args,omitempty"`
	PassArgs    bool     `json:"pass_args,omitempty"`
	Timeout     string   `json:"timeout,omitempty"`
}

func (c Connectors) HTTPTimeoutDuration() (time.Duration, error) {
	if strings.TrimSpace(c.HTTPTimeout) == "" {
		return 15 * time.Second, nil
	}
	d, err := time.ParseDuration(c.HTTPTimeout)
	if err != nil || d <= 0 {
		return 0, fmt.Errorf("connectors.http_timeout must be a positive Go duration")
	}
	return d, nil
}

func (a LocalConnectorAction) TimeoutDuration() (time.Duration, error) {
	if strings.TrimSpace(a.Timeout) == "" {
		return 15 * time.Second, nil
	}
	d, err := time.ParseDuration(a.Timeout)
	if err != nil || d <= 0 {
		return 0, fmt.Errorf("timeout must be a positive Go duration")
	}
	return d, nil
}

func validateConnectors(c Connectors) []error {
	var errs []error
	known := make(map[string]bool, len(NativeConnectorNames))
	for _, name := range NativeConnectorNames {
		known[name] = true
	}
	seen := map[string]bool{}
	for _, raw := range c.Enabled {
		name := strings.TrimSpace(raw)
		if !known[name] {
			errs = append(errs, fmt.Errorf("connectors.enabled contains unknown native connector %q", raw))
		} else if seen[name] {
			errs = append(errs, fmt.Errorf("connectors.enabled contains duplicate %q", name))
		}
		seen[name] = true
	}
	if _, err := c.HTTPTimeoutDuration(); err != nil {
		errs = append(errs, err)
	}
	for _, raw := range c.AllowPrivateCIDRs {
		if _, err := netip.ParsePrefix(strings.TrimSpace(raw)); err != nil {
			errs = append(errs, fmt.Errorf("connectors.allow_private_cidrs %q: %w", raw, err))
		}
	}
	for name, profile := range c.LocalProfiles {
		if strings.TrimSpace(name) == "" {
			errs = append(errs, fmt.Errorf("connectors.local_profiles contains an empty name"))
		}
		if len(profile.AllowedRoots) == 0 {
			errs = append(errs, fmt.Errorf("connectors.local_profiles.%s.allowed_roots must not be empty", name))
		}
		for _, root := range profile.AllowedRoots {
			if !filepath.IsAbs(strings.TrimSpace(root)) {
				errs = append(errs, fmt.Errorf("connectors.local_profiles.%s root %q must be absolute", name, root))
			}
		}
		actionNames := map[string]bool{}
		for index, action := range profile.Actions {
			if strings.TrimSpace(action.LogicalName) == "" {
				errs = append(errs, fmt.Errorf("connectors.local_profiles.%s.actions[%d].logical_name is required", name, index))
			}
			if actionNames[action.LogicalName] {
				errs = append(errs, fmt.Errorf("connectors.local_profiles.%s has duplicate action %q", name, action.LogicalName))
			}
			actionNames[action.LogicalName] = true
			if !filepath.IsAbs(strings.TrimSpace(action.Command)) {
				errs = append(errs, fmt.Errorf("connectors.local_profiles.%s.actions[%d].command must be absolute", name, index))
			}
			if _, err := action.TimeoutDuration(); err != nil {
				errs = append(errs, fmt.Errorf("connectors.local_profiles.%s.actions[%d].%w", name, index, err))
			}
		}
	}
	rightSizeBindings := map[string]bool{}
	for index, binding := range c.RightSize {
		where := fmt.Sprintf("connectors.right_size[%d]", index)
		tenantID := strings.TrimSpace(binding.TenantID)
		connectorName := strings.TrimSpace(binding.Connector)
		if _, err := uuid.Parse(tenantID); err != nil {
			errs = append(errs, fmt.Errorf("%s.tenant_id must be a UUID", where))
		}
		if !connectorRightSizeName.MatchString(connectorName) {
			errs = append(errs, fmt.Errorf("%s.connector must be a lowercase connector key", where))
		}
		key := tenantID + "\x00" + connectorName
		if rightSizeBindings[key] {
			errs = append(errs, fmt.Errorf("%s duplicates tenant/connector %q/%q", where, tenantID, connectorName))
		}
		rightSizeBindings[key] = true
		endpoint, err := url.Parse(strings.TrimSpace(binding.Endpoint))
		if err != nil || endpoint.Host == "" || endpoint.User != nil || endpoint.RawQuery != "" || endpoint.Fragment != "" ||
			(endpoint.Scheme != "https" && (!c.AllowInsecureHTTP || endpoint.Scheme != "http" || !isLoopbackHost(endpoint.Hostname()))) {
			errs = append(errs, fmt.Errorf("%s.endpoint must be an absolute HTTPS URL without userinfo, query, or fragment; explicit insecure http is loopback-only", where))
		}
		secretRef, err := url.Parse(strings.TrimSpace(binding.TokenRef))
		if err != nil || secretRef.Scheme != "secret" || strings.Trim(secretRef.Host+secretRef.Path, "/") == "" || secretRef.User != nil || secretRef.Fragment != "" {
			errs = append(errs, fmt.Errorf("%s.token_ref must use secret://name", where))
		}
	}
	return errs
}
