import type { AttestedSVIDPreview } from "@/lib/api-types.gen";

export const attestedPreviewFixture: AttestedSVIDPreview = {
  capability: "workload_attested_issuance",
  ready: true,
  effect_free: true,
  method: "k8s_sat",
  requester: "workload-owner@example.test",
  trust_domain: "workloads.example.test",
  supported_methods: ["k8s_sat"],
  requested_ttl_seconds: 600,
  effective_ttl_seconds: 600,
  default_ttl_seconds: 600,
  max_ttl_seconds: 3600,
  ttl_defaulted: false,
  ttl_clamped: false,
  required_permission: "certs:issue",
  attestation_verification: "execution_only",
  payload_sha256: "a".repeat(64),
  public_key_sha256: "b".repeat(64),
  preview_writes: [],
  preview_external_effects: [],
  preview_signer_calls: [],
  execution_writes: ["Record one certificate and its verified attestation."],
  execution_external_effects: [],
  execution_signer_calls: ["Sign one X.509-SVID after verifying the proof."],
  steps: ["Review the exact request.", "Verify the proof and sign once.", "Read the certificate and audit evidence."],
  blockers: [],
  recovery_steps: ["Retry the unchanged request with the same Idempotency-Key."],
  data_handling: ["Only request digests are returned by preview."],
};
